(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 728,
	height: 90,
	fps: 24,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



(lib.background = function() {
	this.spriteSheet = ss["clash_728x90_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.book1 = function() {
	this.spriteSheet = ss["clash_728x90_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.book2 = function() {
	this.spriteSheet = ss["clash_728x90_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.logo = function() {
	this.spriteSheet = ss["clash_728x90_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.nouvelle_serie = function() {
	this.initialize();

	// Calque 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ANMBWQgMgFgJgLQgJgKgFgMQgFgNAAgOQAAgOAFgLQAFgNAJgLQAJgKAMgGQAMgFAPAAQAQAAAOAHIAAAgQgFgHgIgDQgIgEgJAAQgJAAgHAEQgIAEgFAGQgFAHgDAHQgDAIAAAJQAAAIADAIQADAIAFAHQAFAHAIADQAHAFAJAAQAIAAAIgFQAIgEAGgGIAAAgQgIAEgHABQgIACgIAAQgNABgNgGgAK/BWQgNgGgJgJQgJgKgEgNQgFgNAAgPQAAgPAFgLQAFgNAIgKQAJgJANgGQAMgGAPABQAPgBAMAGQANAGAJAJQAJAKAFANQAEALAAAPQAAAPgEANQgFANgJAKQgJAJgMAGQgNAGgPgBQgPABgMgGgALKgTQgIADgFAGQgFAGgDAHQgDAHAAAJQAAAIADAIQACAIAEAIQAFAGAIAEQAIAEAKABQALgBAHgEQAIgEAFgGQAFgIACgIQACgIAAgIQAAgJgDgHQgCgHgGgGQgFgGgHgDQgIgEgJAAQgJAAgHAEgAHaBWQgMgFgKgLQgJgKgFgMQgEgNAAgOQAAgOAEgLQAFgNAJgLQAJgKAMgGQANgFAOAAQAQAAAPAHIAAAgQgGgHgIgDQgIgEgIAAQgJAAgIAEQgHAEgGAGQgFAHgCAHQgDAIAAAJQAAAIADAIQACAIAGAHQAFAHAHADQAIAFAJAAQAIAAAIgFQAIgEAGgGIAAAgQgIAEgIABQgHACgIAAQgOABgMgGgAgOBVQgKgIgIgMIASgQQACAHAHAGQAFAGAIAAQAIAAAFgGQAEgGAAgHQAAgFgBgDIgFgHIgHgDIgIgEIgCgBIgLgFIgJgIQgEgEgCgGQgCgEAAgIQAAgIADgIQADgHAFgFQAFgGAIgDQAFgDAIAAQAKgBALAFQAKAEAGAHIgMASQgEgFgFgDQgFgDgGAAQgHAAgFAFQgEAEAAAHQAAAFAEAEQAFACAKAFIANAFQAFADAFAEQAFAFADAHQADAHAAAJQAAAVgMANQgMAMgVAAQgLAAgLgGgAnaBbIg0iIIAcAAIAhBYIAAAAIAehYIAdAAIg1CIgApeBYQgKgFgGgIQgGgHgDgLQgDgLAAgNIAAhOIAbAAIAABJIAAAPIADAMQADAGAFAEQAFADAIABQAIgBAEgDQAFgEADgGQACgGABgGIABgPIAAhJIAaAAIAABOQAAANgDALQgDAKgGAJQgGAHgJAFQgKADgNAAQgOAAgJgDgArlBWQgNgGgIgJQgJgKgFgNQgEgNAAgPQAAgPAEgLQAFgNAJgKQAJgJAMgGQANgGAPABQAPgBAMAGQAMAGAJAJQAJAKAFANQAFALAAAPQAAAPgFANQgFANgIAKQgJAJgNAGQgMAGgPgBQgPABgNgGgAragTQgHADgGAGQgFAGgCAHQgDAHAAAJQAAAIACAIQACAIAFAIQAFAGAHAEQAIAEALABQAKgBAIgEQAIgEAEgGQAFgIACgIQACgIAAgIQAAgJgCgHQgDgHgFgGQgFgGgIgDQgHgEgJAAQgJAAgIAEgAssBaIhIhcIAAAAIAABaIgaAAIAAiJIATAAIBHBcIAAhYIAbAAIAACHgAQ/BYIAAiFIBGAAIAAAXIgsAAIAAAbIArAAIAAAXIgrAAIAAAlIAsAAIAAAXgAPLBYIAAiFIAlAAQAPgBAMAGQAMAEAJAJQAIAKAFANQAFAKAAAPQAAAOgFAMQgFAMgJAKQgIAJgNAFQgMAFgOAAgAPlBBIAEAAQAYAAALgMQAKgLAAgWQAAgqgtAAIgEAAgAJvBYIAAg9IgxAAIAAA9IgaAAIAAiFIAaAAIAAAzIAxAAIAAgzIAbAAIAACFgAEsBYIAAiFIBGAAIAAAXIgsAAIAAAbIArAAIAAAXIgrAAIAAAlIAsAAIAAAXgAD/BYIAAiFIAaAAIAACFgADWBYIghg3IgBAAIAAA3IgaAAIAAiFIAkAAQAVgBAMAKQAMAKAAAVQAAAMgHALQgIALgNACIAnA5gAC0APIAEAAQAMAAAGgFQAHgEAAgKQAAgMgHgEQgGgEgMAAIgEAAgABCBYIAAiFIBGAAIAAAXIgsAAIAAAbIArAAIAAAXIgrAAIAAAlIAsAAIAAAXgAimBYIAAiFIBGAAIAAAXIgsAAIAAAbIArAAIAAAXIgrAAIAAAlIAsAAIAAAXgAjuBYIAAiFIAaAAIAABuIAlAAIAAAXgAk3BYIAAiFIAaAAIAABuIAmAAIAAAXgAmPBYIAAiFIBGAAIAAAXIgsAAIAAAbIArAAIAAAXIgrAAIAAAlIAsAAIAAAXgAvnBYIgKgcIgvAAIgLAcIhZAAIAAiFIAaAAIAABuIAlAAIAAAQIAziCIAUAAIA0CJgAv4AlIgRgvIgBAAIgPAvIAhAAgABWg8IAVgfIATAMIgcAbg");
	this.shape.setTransform(115.8,9.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,231.6,18.4);


(lib.jay_crownover = function() {
	this.initialize();

	// Calque 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#ED2256").s().p("AJEBXIg/ipIAiAAIAoBuIABAAIAlhuIAiAAIhACpgAGQBQQgPgHgLgMQgLgMgGgQQgFgPAAgSQAAgRAGgQQAFgQALgMQALgMAPgGQAQgHASAAQASAAAPAHQAPAGALAMQALAMAGAQQAGAQAAARQAAASgGAPQgGAQgKAMQgLAMgPAHQgQAHgSAAQgTAAgPgHgAGegxQgKAEgGAIQgGAIgEAJQgDAKAAAKQAAAIADAKQACAKAGAIQAGAJAKAFQAJAFANAAQANAAAJgFQAJgFAGgJQAGgIADgKQACgKAAgIQAAgKgDgKQgDgJgHgIQgGgIgJgEQgJgFgLAAQgLAAgJAFgAiYBQQgPgHgLgMQgLgMgGgQQgFgPAAgSQAAgRAGgQQAFgQALgMQALgMAPgGQAQgHASAAQASAAAPAHQAPAGALAMQALAMAGAQQAGAQAAARQAAASgGAPQgGAQgKAMQgLAMgPAHQgQAHgSAAQgTAAgPgHgAiKgxQgKAEgGAIQgGAIgEAJQgDAKAAAKQAAAIADAKQACAKAGAIQAGAJAKAFQAJAFANAAQANAAAJgFQAJgFAGgJQAGgIADgKQACgKAAgIQAAgKgDgKQgDgJgHgIQgGgIgJgEQgJgFgLAAQgLAAgJAFgAmWBQQgPgHgLgMQgLgMgGgQQgGgPAAgRQAAgQAGgQQAGgQALgMQALgMAPgIQAPgHASAAQATAAASAKIAAAnQgHgJgKgFQgKgEgKAAQgLAAgJAFQgKAEgGAJQgGAHgEALQgDAKAAAJQAAALAEAKQADAKAGAIQAHAIAJAEQAJAFALAAQAKAAAKgFQAJgFAIgHIAAAmQgKAFgKACQgJADgJAAQgRAAgPgHgAtrBSQgJgEgHgHIAVgXQABAEAEADQAEADAEABQAEAAADgEQADgDABgEIACgMIAAgPIAAhnIAhAAIAABsQAAAPgCAJQgCAJgGAJQgGAKgKAEQgKAFgLAAQgJAAgIgFgAE5BWIhYhyIAABuIggAAIAAioIAXAAIBXByIABAAIAAhuIAgAAIAACogABoBWIghhqIgBAAIgfBqIgYAAIgyioIAhAAIAgBwIAAAAIAhhxIAUAAIAiBxIAAAAIAhhwIAiAAIg4CogANVBSIgphDIAABDIggAAIAAikIArAAQAaABAPAMQAPAMAAAaQAAARgJANQgJALgQADIAvBFgAMsgFIAEAAQAPAAAIgFQAHgHAAgNQAAgPgHgFQgIgFgPAAIgEAAgAKgBSIAAikIBWAAIAAAdIg1AAIAAAkIAzAAIAAAaIgzAAIAAAtIA1AAIAAAcgAjyBSIgphDIAABDIggAAIAAikIArAAQAaABAPAMQAPAMAAAaQAAARgJANQgJALgQADIAvBFgAkbgFIAEAAQAPAAAIgFQAHgHAAgNQAAgPgHgFQgIgFgPAAIgEAAgApcBSIAAhMIgzhYIAlAAIAdA6IAgg6IAmAAIg1BYIAABMgAqsBSIgNgiIg5AAIgOAiIgiAAIBAioIAaAAIA+CogArCAVIgVg6IgSA6IAnAAg");
	this.shape.setTransform(89.2,8.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,178.5,17.5);


(lib.discover_bold = function() {
	this.initialize();

	// Calque 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJBYQgRgQAAgbIAAhjIAgAAIAABeQAAASAHAIQAHAJARAAQAQAAAIgJQAHgIAAgSIAAheIAhAAIAABjQAAASgHANQgIANgPAHQgPAHgUAAQgeAAgPgPgAi7BSQgTgVAAgnQAAglATgVQATgUAlAAQAkgBATAWQATAUAAAmQAAAmgTAVQgUAVgkAAQgkAAgTgVgAihgQQgLAOAAAZQAAAZAKAOQAKANAUAAQAoAAAAg0QAAg0gnAAQgUAAgKANgAlIBSQgSgVAAgmQAAgXAIgSQAJgTARgJQARgKAWAAQAXgBAXAMIgLAbQgIgFgJgCQgJgDgJAAQgTAAgKANQgKAOAAAYQAAA0AnAAQARABAXgJIAAAcQgTAIgYAAQgiAAgSgVgAJOBlIgmg8IgSAAIAAA8IghAAIAAibIAuAAQAgAAAPALQAQANAAAXQAAAMgIALQgIAKgOAHIAuBEgAIWAOIALAAQAQgBAHgEQAIgGAAgJQAAgMgIgEQgHgFgRAAIgKAAgAGsBlIAAibIAhAAIAACbgAF0BlIgmg8IgSAAIAAA8IghAAIAAibIAuAAQAgAAAPALQAQANAAAXQAAAMgIALQgIAKgOAHIAuBEgAE8AOIALAAQAQgBAHgEQAIgGAAgJQAAgMgIgEQgHgFgRAAIgKAAgACuBlIg2ibIAiAAIAdBbIAGATIADAQQABgKAHgZIAehbIAhAAIg1CbgAnOBlIAAibIBaAAIAAAbIg5AAIAAAhIA1AAIAAAbIg1AAIAAAoIA5AAIAAAcgApxBlIAAibIAxAAQAmAAAWAUQAVAVAAAiQAAAngWAUQgWAVgqAAgApQBJIAOAAQAwABAAg0QAAgxgsAAIgSAAgAm1hDIAAgDQATgVAHgLIAkAAIAAADIgTAQIgVAQg");
	this.shape.setTransform(62.7,10.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,125.4,20.7);


(lib.clash_top = function() {
	this.initialize();

	// Calque 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#ED2256").s().p("AgLALIgFgJQAIgCADgBIAFgJIARABIgCAEQgEAFgCAHIgGAAIgIADIgEABg");
	this.shape.setTransform(251.2,22.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#ED2256").s().p("AgOASQgCgCgEgFIADgCQAHgFABgDIACgKIAAgLIABgCQAMACAPgCIgWAtIgNgFg");
	this.shape_1.setTransform(255.9,23.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#ED2256").s().p("AAAAOIgJgDQgBgFgCgDQgEgEAGgHIAEgFIAFAAQAIgEAHAKQAAAHgHALQgBAEgEAAIgCgBg");
	this.shape_2.setTransform(146,52.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#ED2256").s().p("AAAAbQAAgCAAgFIAAgHIgEgCQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQgBAAgBgBIgHgDIAAgEIAJgWQADgCAEACQADACACAAIAEAIQAFAGgDAHIABACQAEADAAAHIABAMIgKAGIgDABIgEgBg");
	this.shape_3.setTransform(142,58.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#ED2256").s().p("AiCCtIAAg8QACgFAAgNIABkLIACgDIAKgKIAPgBIDEAAQAOABAEACIAHAAIAJAKIAABuQABAKgDADIAAAJIAADBQgBAHgHAAIgIAAIgHABQgDAAgDABQgCABgGAAIgKAAQgHAAgDADIgIAAQgNAAgDACIgLABQgKAAgEABIgKABIgHAAQgFAAgBACIgHABQgNAAgEACIgJABQgJAAgEABIgGABQgPABgFACIgHAAIgQACIgLABQgMAAgDACIgDAAQgEgEgBgJg");
	this.shape_4.setTransform(367.1,21.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#ED2256").s().p("AhzDQIgGgPQgHgTACgSQACgDAAgIQABgHABgFIAAgGIACgFQADgDABgEIABgHIAAgIIgIgHQgFgFADgFQAFgKgEgMQgCgKAAgPIAAiNQgBgLgCgDIgBgFIAAhFQAIgFgCgHQAHgGAKAAIA8AAIAJAAQAGABAEACQAEACADgDQAEgCAHAAIARAAQAHABAEgCIAFgBIBfAAIAMAMIABAQIAAFuQgCAFgEAAIgRADQgKACgGgBIgDAAQgCACgNAAIgRACIgEABIgFgBIgOADIgLABIgOACQAAABgHAAQgLAAgGABIgKABQgJAAgDACIgKAAIgNADQgBABgHAAIgSABIgMABQgJAAgDADQgEgBgBgFg");
	this.shape_5.setTransform(314.3,24.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#ED2256").s().p("AiIFYIAAgLIAAgVQAAgEABgHQACgIAAgDIABgLIACgKQACgDABgHQABgHACgDIAIgBQAIAAADgBQACgCAGABQAJAAACgBQgBgLgJgEIgKgFQAAgRgLgHIgJABQgGgIABgIIABgEQADgDgBgEIgDgGQgHgSAEgKIABgFQAAgJAFgKQgEgEABgHQAAgOgCgFIAAgJIAAidQAAgJgCgFIgBgKIAAifIAAgJQAAgFgDgDIAAgEIAAg6IAMgNIAfAAIAEABQADACAMAAIAqAAQANAAADADIAKAAQAGAAADgBQACgCAGAAIAuAAQAIAAADgCIAHgBIAyAAQAHABAEAEQAEAEABAHIAAEJQAAAMgCAFIgBAHIAADRQAAAHACADIABAKIAABTQAAAJACACIgDAFQACASgDAIIgBAIIgBALQgUAFgLgBIgDAAQgFACgQAAIgEAAQgEADgGAAIgLAAQgHAAgDACQgBABgIAAIgRACIgNAAIgIACIgKABIgIAAQgFABgDACIgHAAQgNAAgFACIgMABQgIAAgDABQgCABgHAAIgIABQgFAAgEACIgKAAIgHABQgEAAgDABIgHABQgCgEAAgHg");
	this.shape_6.setTransform(84.8,36.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#ED2256").s().p("AjREHIgBgDQAAgDgDgCQgIgEgFgKQgKgVgGgTIgBgJQgBgKgBgDQgBgBAAgNQAAgIADgDQgFgJgBgJIgCgKIAAgLIgBgEQgCgCAAgEIAAgHIAAgXQAAgKACgDIABgIIAAgKQAAgGACgEIAAgHIABgHQACgCAAgHQAAgJACgCIABAAIACgUQAAgGADgFQADgDAAgIQgBgJAGgEQAHgFABgKQAEgLABgGQABgIAKgOQAJgOAEgCIADgCQAKgFAAgKIAHgMIAZgYQALgLANgCQAFgBABgEQACgGAJgFIAQgKIAQgIIAGgBQADAAAKgEIAEgCQADAAAGgBQAFgCADAAQAFABAEgDQAAAAABAAQAAAAABAAQABAAAAAAQABAAAAAAQAGAEAEgGQAEgEAIAAQAJABAFgEQACgBAFACIANAEQAKgOACgFIAMAFQAIAEADAFQAFgDADgEIAEgGQAFgFAGADIAMAFIgBAGIACABQAIgGALAIQAFAEAFAAIADAAIAFACQADABADgBIAKgEIALAKIALABIAYACIAFABQAJAEAGgFQAFgEAGACIALADQABAAAAABQABAAAAABQABAAAAABQAAAAAAABIAAAGIAAAbQAAAMgCAEIAAAJIAABTIgBAMIAGAHIAAA9QAAAIACADQABABAAAEIAAAdIgJAKIgOAAIgCgDQgBgBAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAIgDACIgBAAIgxgSQgHABgSgGIgOgEQAAgIgJgEIgKgHIgBgDQgDABgDALIgJABQgCAIgDACIgNAOIgHAGQgKAEACAKIgBAEQgPALgMgBQAAADACACIADADQADAEAAACQgBAFAGALIACACQAEAHgHADIgIAFIgDAGQADADAGABQAHACACABIABAMQASAVAFAFIAcAcQALALAFADIAHAGIAGAHIgBACQgHgBgMACQgNACgHgBIgDAAQgDADgQAAIgJACQgBABgFAAIgKABQgGgBgFACIgKAAIgNACIgKABIgHAAQgDABgDACIgDABIgFAAQgMAAgFABIgKABQgKAAgEACIgIAAIgKABQgGAAgEACIgLABQgIAAgEABQgCABgJAAQgLAAgDACIgGABQgNAAgEACIgEABIgFAAIgPACIgMAAIgMACQgBABgEAAIgDAAgAhUCQQgCAFgIAHQgCADACACIAHgGQAEgEAEgBIAAgFIgDgCIgCABgAgqCOIAAACIABABIADgCIgBgCIgDABgAABCAIADAIIAHACQgCgCABgGQABgEgDgBgAhyAYQAAAAAAABQgBAAAAABQAAAAABABQAAABAAAAIAEACIACgDIADgHIgDAAQgDAAgDAEgAhdgwIAAALIgBAMQgBADgHAFIgDACQADAFADACIANAFIAYgwQgPACgPgBgAiJgqQgDADgIADIAFAJIACAAIAEgBIAKgEIAGAAQACgIAEgFIACgFIgSgBg");
	this.shape_7.setTransform(264.4,26.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#ED2256").s().p("AkIGIIgKgBQgGgIgEgQIgCgGQgBgEAAgDIgCgDIgDgQIgDgLIgBgFQAAgDgCgCIAAgHIgCgMIAAgIIAAgLQgBgGgCgEIAAgFQAAgKgDgDIgBgFIgCgPIAAh7IABgJIABgKIAAgGQABgEACgCIABgCIABgMIABgLQAEgMgBgGQAGgLAAgNIABgDQAFgMACgOIAFgOIADgJQAAgGACgDIAFgPQACgJAEgFQACgCABgGQADgQALgRIACgGIAPgYIACgEIAMgTQAJgKADgHQAEgDAGgIIAKgMQAFgGABgCQAAgBAAAAQAAAAABgBQAAAAAAgBQABAAABAAIAIgKIAEgGIAGgFQADgDABgEIADgDQAIgIADgGQAEgFAEgCIALgJQAHgIAEgBQAEgCAIgHIAOgKQAJgGAGgCQADgEAJgEQAIgEAEgDIAQgIQAJgFAHgCIACgBQAJgFAXgIIATgGIAegIIAOgCQAFAAAEgCQABgBAFAAIANAAIAFAAQAFgDAIAAIAOAAIACABQAFADAGAAIAMgBIALAAIAEABQAEACAIAAIAMAAQAIAAADACQAEABAHAAQAKAAAEACQACABAHAAQAJAAADACIAEAAQAFgBAJACIAQACIABAIIAAAIQAAAFABADIABAIIAAAuQAAAQACAFIAAAIIAAA1QAAAIADADIABAGQABAqgBArIgBAEQgDADAAAKQAAANgCAGIAAAPQAAAIgGACIgEACIgIADQgCAAgGgDIgVgIIgNgDQgIgCgFgDQgDABgGgCIgJgCIgSgEIgIgBIgHAAQgDgBgDgCIgXAAIgCABQgDAEgJAAIgFAAQgFgBgHACIgMADQgGABgLAGIgQAJIgLAJIgPANQgJAHgGAGIgRATIgNASIgIASIgGAOIgEAMIgIASIgGAOQgBALgBADQAAAFgBAKQgCAKABAFQAAAJgDADIgBAJQAAAFACAEIACADQgBAHADAOIACAMQABAIACAEIADAMQABAKAEAHQABABAAAFQABAEABACQADANAIAZQADAHADAGIAgAgIAHAFIAIAGQgHAFgDAAIgOAAQgHAAgDACIgJABIgHAAQgEAAgEACIgKABQgKAAgEABIgMABQgJAAgDACQgCABgJAAIgHAAQgEAAgDACQgCABgHAAIgIAAQgFAAgDACIgLAAQgKAAgDACIgKABQgLAAgEACIgEABIgEAAIgRACIgKAAQgMABgCACIgIAAIgIAAQgGABgDACIgGAAQgMAAgHACIgGABIgEAAg");
	this.shape_8.setTransform(31.1,40);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#ED2256").s().p("AlTEyIgBgBQAIgQACgIQADgMgEgHQgDgDADgDQAFgFAGgSIAMgnQADgJADgLQABgEACgBQADgDACgFIAFgIQABgBAAgFQAAgLACgDQAAgBAAAAQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgIADgHIAIgaIAMgkQAFgKAAgGQACgDABgGIAEgKIAJgaQAEgSAEgIQAGgWAFgJIABgKIAJgZIAEgQIAGgUIAFgNQADgIAAgGIABgDQAGgPADgTIADgIIAFgSQADgFACgKIAEgQQAEgGgBgFQAAgCABgEIACgGQAAgFADgEQABgEABgGQAAgGAHAAIEwAAQAHAAABABQABABADAGIAIAZIAGASIAZBJIAGASIAMAlIAEAOQABAIAEAHQAFALAHAZIAMAlIAIAYIAIAXIAGAPQACAJADAFQAAAHAFALIANAqIANAlIAMAkQACAEABAKQAGANADAPIADAFQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAIgEAAQgNAAgDACIgHABIgJAAQgGAAgDACIgMAAIgLACQgBABgIAAIgIABQgFAAgEACQgCABgDgBIgFAAQgKAAgEACIgMABQgJAAgDACIgHAAIgJABQgHAAgDACIgEABIgEgBIgIABQgFAAgDABIgLABQgKAAgEACIgDABIgGAAIgHAAQgFAAgDACIgHABQgOAAgEABIgIABIgIAAQAAgEgDgGIgEgJIgDgKIgFgJQgFgMgBgHIgHgSIgPgmQgEABAAAFIgGASQgCAJgCAKIgKAeIgDAOIgJAcIgCAFQgDAEgEAAQgKgBgJADIgJABQgKAAgDACIgEABIgFgBIgIAAQgFABgDACIgHAAIgSACIgNABQgGAAgFACIgJABQgMAAgFACIgDABIgGgBIgOACIgNABIgMACQgBABgIAAIgMACQgCABgFAAIgTACIgNAAQgHAAgEACIgHABIgLAAQgGAAgEADg");
	this.shape_9.setTransform(180.4,32.6);

	this.addChild(this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,380.2,79.2);


(lib.clash_text = function() {
	this.initialize();

	// Calque 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHHEbQgEgEAAgHQAAgFAEgEQAEgFAGABQAGgBAEAFQAFAEgBAFQABAHgFAEQgEAEgGAAQgGAAgEgEgAFxEbQgJgDgFgIQgFgHgDgJQgDgJAAgMIAAhIIAYAAIAABEIAAANIADALQADAFAEADQAFADAGAAQAHAAAFgDQAFgDABgFQACgGABgFIABgNIAAhEIAXAAIAABIQAAAMgCAJQgEAJgFAHQgEAIgJADQgJAEgMAAQgMAAgIgEgAD6EaQgMgFgHgIQgIgJgEgMQgEgLAAgNQAAgOAEgLQAEgMAIgIQAIgJALgFQALgFAOABQAMgBALAFQAMAFAHAJQAIAIAFAMQAEALAAAOQAAANgEALQgFAMgIAJQgHAIgMAFQgKAFgNAAQgOAAgLgFgAEEC7QgHADgEAGQgFAFgCAHQgDAIAAAHQAAAHACAHQACAHAEAHQAEAFAIAFQAGADAKAAQAIAAAHgDQAHgFAFgFQAEgHABgHQACgHAAgHQAAgHgCgIQgCgHgFgFQgEgGgHgDQgHgEgHAAQgJAAgGAEgAhEEbQgIgDgGgIQgFgHgDgJQgCgJAAgMIAAhIIAXAAIAABEIAAANIAEALQACAFAEADQAEADAIAAQAGAAAFgDQAEgDACgFQACgGABgFIABgNIAAhEIAXAAIAABIQAAAMgDAJQgCAJgGAHQgEAIgJADQgJAEgLAAQgNAAgIgEgAi7EaQgLgFgIgIQgIgJgEgMQgEgLgBgNQABgOAEgLQAEgMAIgIQAIgJALgFQALgFAOABQANgBALAFQALAFAIAJQAHAIAFAMQAEALAAAOQAAANgEALQgFAMgHAJQgIAIgLAFQgLAFgNAAQgOAAgLgFgAixC7QgHADgEAGQgFAFgDAHQgCAIAAAHQAAAHACAHQACAHAEAHQAFAFAHAFQAGADAKAAQAJAAAHgDQAGgFAFgFQAEgHABgHQADgHAAgHQAAgHgDgIQgCgHgFgFQgFgGgGgDQgHgEgHAAQgJAAgGAEgAkoEeIgahNIgLBLIgYAAIAUh7IARAAIAeBPIAdhPIAQAAIATB7IgZAAIgJhLIAAAAIgbBNgACSEcIAAh5IA9AAIAAAVIglAAIAAAaIAjAAIAAAVIgjAAIAAA1gABAEcIgdgxIAAAAIAAAxIgYAAIAAh5IAhAAQASAAALAJQAKAJAAATQABAMgHAJQgGAKgMACIAiAzgAAjDbIADAAQALAAAFgEQAGgEAAgLQAAgKgGgDQgFgEgLAAIgDAAgAl+EcIgKgZIgpAAIgKAZIgZAAIAvh7IASAAIAuB7gAmODvIgPgrIAAAAIgOArIAdAAgABXA5QgFgEAAgHQAAgFAFgEQADgFAHAAQAGAAAEAFQAEAEAAAFQAAAHgEAEQgEAEgGAAQgHAAgDgEgAiFA4QgLgFgIgIQgIgJgDgMQgFgLAAgLQAAgOAFgLQADgMAIgIQAJgJAKgFQALgFAOABQANgBALAFQALAFAIAJQAIAIAEAMQAFALgBAOQABALgFALQgEAMgIAJQgHAIgMAFQgLAFgNAAQgOAAgLgFgAh7gmQgGAEgFAFQgEAGgDAIQgDAGABAIQAAAFABAHQACAIAFAGQAEAFAHAFQAHADAJAAQAJAAAHgDQAHgFAEgFQAFgGABgIQACgHAAgFQAAgIgDgGQgCgIgEgGQgFgFgHgEQgGgDgIAAQgIAAgHADgAjrA3QgJgGgHgMIAPgPQADAIAGAGQAFAEAIAAQAHAAAEgEQAEgGAAgHIgBgHIgFgGIgFgDIgHgDIgDgBIgLgDQgEgDgEgEQgDgEgCgEQgCgGAAgGQAAgIACgHQADgGAFgFQAFgFAGgDQAHgCAGAAQAJAAAKADQAJAEAGAFIgLARQgDgEgFgDQgEgDgGAAQgGAAgEAEQgGAEAAAGQAAAFAGADQADADAJAEIAMAGQAFACAEAEQAEADADAFQACAHAAAIQABASgLAMQgLALgSAAQgMAAgJgGgAAwA9Ig+hTIAAAAIAABQIgXAAIAAh5IARAAIA9BSIABAAIAAhPIAXAAIAAB5gAkfA6IAAh2IAYAAIAAB2gAlDA6IgdgwIAAAAIAAAwIgYAAIAAh2IAgAAQATgBALAKQALAIgBATQAAAMgGAJQgHAJgMABIAjAzgAlggFIADAAQALAAAGgEQAFgEAAgKQAAgLgFgEQgGgDgLAAIgDAAgAnMA6IAAh2IAfAAQAVgBALAKQAKAIABAUQAAASgKAIQgLAKgSAAIgMAAIAAAtgAm1gFIAGAAQAKAAAGgDQAEgFAAgKQAAgLgEgEQgGgDgLAAIgFAAgADvikQgFgDAAgHQAAgFAFgFQAEgDAGAAQAFAAAFADQAEAFAAAFQAAAHgEADQgFAFgFAAQgGAAgEgFgABaikQgKgFgJgJQgIgIgEgMQgEgMgBgMQABgMAEgMQAEgLAIgKQAIgJALgFQALgFANAAQAOAAANAHIAAAdQgFgHgHgDQgIgEgHAAQgIAAgHAEQgGADgEAHQgFAFgDAHQgCAIAAAIQAAAIACAHQADAHAFAGQAEAGAGADQAHADAIAAQAHAAAIgDQAHgEAFgFIAAAcIgOAFQgHACgGAAQgNAAgLgFgAkoikQgLgFgIgJQgIgIgFgMQgEgMAAgMQAAgOAEgMQAFgLAIgIQAIgKALgEQALgFANAAQANAAALAFQALAFAIAIQAIAJAFALQADAMAAAOQAAAMgDAMQgFAMgIAIQgIAJgLAFQgKAFgOAAQgNAAgLgFgAkfkDQgGADgFAGQgEAFgDAHQgCAHAAAIIACAOQACAHAEAHQAEAFAHAEQAGAEAKAAQAJAAAHgEQAHgEAEgFQAEgHACgHIACgOQAAgIgCgHQgCgHgFgFQgFgGgHgDQgGgEgIAAQgIAAgHAEgAmwifIguh8IAZAAIAdBRIAAAAIAbhRIAZAAIgvB8gAAaigIg9hUIAAAAIAABSIgYAAIAAh8IARAAIA9BUIABAAIAAhRIAYAAIAAB7gACciiIAAh5IA+AAIAAAUIgnAAIAAAbIAmAAIAAAVIgmAAIAAAgIAnAAIAAAVgAiJiiIAAh5IA/AAIAAAUIgoAAIAAAbIAmAAIAAAVIgmAAIAAAgIAoAAIAAAVgAjJiiIAAh5IAXAAIAABkIAiAAIAAAVgAlviiIAAh5IAYAAIAAB5g");
	this.shape.setTransform(52.2,36.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(4.2,8,96,57.5);


(lib.clash_bottom = function() {
	this.initialize();

	// Calque 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#ED2256").s().p("AAAACIAAgDIAAAAIABADg");
	this.shape.setTransform(36.2,53.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#ED2256").s().p("AgBAAIADgCQABACgBADg");
	this.shape_1.setTransform(43.3,60);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#ED2256").s().p("AgBAAIABAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIABABIgCACg");
	this.shape_2.setTransform(53.6,59.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#ED2256").s().p("AAAgBIABACQAAAAAAAAQAAAAgBAAQAAABAAAAQAAAAAAAAg");
	this.shape_3.setTransform(43.7,59.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#ED2256").s().p("AAAACQAAAAAAAAQAAAAAAAAQAAgBAAAAQgBAAAAgBIABgBIACABQAAAAAAABQAAAAAAABQgBAAAAAAQAAAAAAAAIgBAAg");
	this.shape_4.setTransform(37.4,62);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#ED2256").s().p("AgBAAQgBAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAgBAAAAQAAAAAAAAQAAAAAAABIADABIgDABQAAAAAAAAQAAgBAAAAQAAAAAAAAQgBgBAAAAg");
	this.shape_5.setTransform(34.6,57.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#ED2256").s().p("AAAAAQAAgDgCgCIACgBQAGAGgFAGIgBABQAAgCAAgFg");
	this.shape_6.setTransform(37.6,48.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#ED2256").s().p("AgDgCQADgDAEAFIgDAEg");
	this.shape_7.setTransform(47.5,60.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#ED2256").s().p("AgEADQACgDACgCQAEgCABAEIgFADIAAAAIgEAAg");
	this.shape_8.setTransform(49.3,59.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#ED2256").s().p("AgEADIAAgBIAAgBIAFgFIADABIABABIgBACIgEAEIgBABIgDgCg");
	this.shape_9.setTransform(36.1,51.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#ED2256").s().p("AgCACIgFgBQACgBAFgBQADgCACgDIADAHIgGAGg");
	this.shape_10.setTransform(39.5,64.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#ED2256").s().p("AgKAIQgCgDABgFIALgCQAFgCACgCQACgCADABIAAAAIgKAPQgGgDgGADg");
	this.shape_11.setTransform(37.9,55.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#ED2256").s().p("AgJAAQgBAAABgDQABgDACgCQABAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAIANAHIgLAKg");
	this.shape_12.setTransform(53.5,48.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#ED2256").s().p("AAHAcIgBgDIgCgOIAAgHIgBgIIgHgFQgDgBgCgEQgEgGAFgEIAGgFQACACAAAEQgBAKAGACIADALIADAKQABACgBAFIgCAEIAAADIACAHIgEgDg");
	this.shape_13.setTransform(50.1,52.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#ED2256").s().p("AgbAVQAFgJgDgHQgCgCgGABQgGAAgDgEQACgEAFgBQABgBAAABQABAAABAAQAAAAABAAQAAABABAAIADADIATgCIAEgMIAFAKIAFAAQAGABADgHIAGgHIAIgBIAIgCIAGABQgFACgFAFIgKAHQgFADADADQAEAGgEAEIgFAEQgDACgDgCQgCgCgFAAQgDAAgBgCQgBgBAAAAQAAAAAAAAQgBAAAAAAQAAAAAAABQgDACgEAAIgIAAIgDAIQAAABAAAAQgBABAAAAQgBAAAAAAQAAAAgBAAIgDgBg");
	this.shape_14.setTransform(48.2,63.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#ED2256").s().p("AgdAxIABgCQAEgEAAgEIABgHIgJgNIgGgEIADgHIAUgFIAEgJIgHgNIgOgFIgCAGIgBgGQAAgFgCgCIAFgLIAGgJQACgEAEAAQAEAAABAFIgKALIAIALQACABALADIgCALIALAHQAJADAHgHIARAIQADADgFAGIgVAMQgBgIgGgEQgCgCgJgEIgNAGIABAHIAGALQACAFgCACIgMAVIgEADg");
	this.shape_15.setTransform(42.7,56.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#ED2256").s().p("AAAAOQgEAAgDgEQgEgFgBgDIAAgIIAAgHIAQAAIAJAJIAAARIgKABIgDAAg");
	this.shape_16.setTransform(234.7,31.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#ED2256").s().p("AgIANQgDgBgCgDQAAAAAAgBQAAgBAAAAQAAgBAAgBQAAAAAAgBIADgGQABgFACgDIADgHIAIACQAEABADAGQAEAFgBADQgBALgIAHQgIgEgFgBg");
	this.shape_17.setTransform(141.4,78.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#ED2256").s().p("ADiC4IgXAAQgKAAgCgCIgHgBIgYAAQgNAAgEgCIgHgBIgfAAQgHAAgDgBIgCgBIgKAAQgGgBgDgCQgGAAgIgCIgMgEIg7gTQgHgEgMgEIgUgHQgXgKgRgJQgUgLgMgKQgOgKgDgCIgFgEIgEgFIgGgEIgEgDIgagaQgCgFgLgKQgFgGAAgCIgCgCQgIgIgPgVIgUgdIgCgEIgGgMQgFgFgFgNIgJgPIgGgMQAAgEgFgIQgGgLgBgGQgGgHAAgFQAFgEALAAQAMAAAFgDQACgBAIABQALAAACgCIAHgBIAQgCIANAAIAKgCIAJgBIAIgBQAGAAACgCIAHAAQAOAAAFgCIAMgBQALAAAEgCQACgBAGAAQANAAAEgCIAKAAIAHgBIAHgBIAMgBIAGAAIAGgCQABgBAGAAIAJAAQAGAAAEgCQADgCAIABQAIAAACgBIAPgBQAIgBAGADQANAFAJAMIAEAIIAGgFIAnARQAKAFAFgBIAIACIAQAFQAEAAAFACIAJADIgDAaQgCABgFAAIgIABIgHAMQACAGADACQADAGgDAGQgDAEgBAGQAAAAAAAAQAAABAAAAQAAAAABABQAAAAABABQAAAAAAAAQABAAAAAAQAAAAABAAQAAAAABgBIAGgFIADgFQADgCADgBIADgCQAFgFAHgGIAPgKIAGgCIAGgLQACgEADgBIAJgEQAFgDAEgBQADAAAEgEQgHgCgCgJIgDgIIATgUQAJgCAHAFIANgNIAMACQAFAAACAFQAGARgGASQgEAFAEAFQAFAKgFANIgDAEQgCACgEgBQgFgBgCADQADABAFAFQAEAEAEABQAAAAAAAAQABABAAAAQABABAAAAQAAABAAABIABAKQAAAGgEAEIADAGIAAAIIAAAWQgBABgFAAQgEABgBACIgEAAQgDgDgBAEQgDAEADADIAHAGIgGAIQABAHAIAEIAMAFQABAAAAABQAAAAAAAAQAAABAAAAQAAABgBAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAIADAGQADAHAAAIIAAAaQAAAJACACIABAGIAAARQAAAKACAEIABAGIAAAWQAAAGgGACIgVALIgNAFQgGADgGAAQgEADgGAAIgLAAgACcBJQACAHgFAJQAEADADgEIADgIIAHAAQAFAAACgCQABAAAAgBQAAAAAAAAQABAAAAAAQAAABAAAAQACACAFAAQAFAAACACQADACADgCIAFgEQAEgEgEgGQgDgFAFgDIAJgHQAGgFAEgCIgFgBIgIACIgIABIgGAHQgDAHgGgBIgFAAIgHgKIgEAMIgUABQgDgEgEABQgFABgCAGQADAEAGAAIACAAQAEAAACABgABeBLQgFACgCACIAFABIAGAFIAGgGIgDgJQgCADgFACgABsgTIAHANIgEAJIgTAFIgEAHIAGAEIAJANIgBAHQAAAEgEAEIgBACIAFAHIADgDIAMgVQADgCgDgFIgGgLIgBgHIANgGQALAEACACQAGAEABAIIAWgMQAEgGgCgDIgSgIQgHAHgJgDIgMgHIABgLQgLgDgBgBIgIgLIAKgLQgCgFgEAAQgEAAgCAEIgGAJIgFALQACACABAFIAAAGIADgGgABIA1QAAAAABABQAAAAAAAAQABABAAAAQAAAAABAAQAAAAABAAQAAAAAAgBQABAAAAAAQAAgBAAgBIgDgDgACrAgIAGAIIADgFQgDgEgDAAIgDABgACDAfIAFAEQACgEgCgDgADrAbIgBACIACACIADgCIgBgDIgBAAIgCABgADCAUQgEADgCAEIAFABIAFgEQAAgBAAgBQAAgBgBAAQAAgBgBAAQAAAAgBAAIgBAAgACIAcQABAAABgBQAAAAABAAQAAAAAAAAQABAAAAgBIgBgDgAArAKQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABQADADAEgCIgEgDIgBgBIgCABgABTgBIAJgRIAAAAQgBAAAAAAQgBAAAAAAQgBAAgBAAQAAAAgBABQgCACgFACIgMADQgCAGACADIAGgCQAEAAAFACgADBhBQgGAFAEAFQACAFADABIAJAEIABALIAAAHIADAOIAAADIAEACIgCgGIABgEIABgDQABgFgBgCIgDgLIgDgMQgIgCABgKQABgFgDgCIgFAFgAA9gdIACAAIgBgFIgBAAgAA+g5IgGAGIAAACIAAABQABAAAAABQABAAAAAAQABAAAAAAQAAAAAAAAIAHgGIABgCIgBgCIgDAAIgBAAgABIhTQADACAAAFQgBAFACABIACgBQAFgHgIgGgADlhaQgDACgBADQgBADABACIAIAJIAOgMIgQgHIgBAAIgBAAg");
	this.shape_18.setTransform(29.9,56.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#ED2256").s().p("AB4DdQgFgDgOAAImDAAQgNAAgHgJIgEgEIAAhtQAAgJACgFIABgJIAAiqIgBgLIACgKQADgGgDgGQgDgHADgGQADgHgCgFIgCgOQAAgFgCgCQgCgDABgKIADAAIAKgBQAGgBADgBIAKAAIAHgBQAEAAACgCIAFgBQAMAAAGgCIAPAAQAHAAAEgCQADgCAHABQAMAAADgCIAIgBIAJAAIAJgCIAKAAIAOgCIAJgBIAIAAQAEAAAEgDQACgBAIABQAKAAAEgCQACgBAHAAQAMAAAEgBIAJgBIAIAAQAFAAADgCIAFAAIAABEQAAAIACADIABAHIAAAUQADAFAPAKQAGAEAHAAIAdgBQAHAAADgBQACgBAIAAICXAAQALAAAEgCIAHAAIBQAAQADAAADADIABAEQAIAHgGAKIgDAHQgEAGADADQADAEgCACQgDAFgCANIgGALIgIAMIAAAHIgCAPQgCAJgEAHQgCAFgDAPIgCAJQgEAHABAGQAAAGgDALIgEAKQgCAIgIATIgBACQgIAIAGAGIgBAMIgEANIgDANIgEAOQgCAGgFAEQgKAIgOAHQgLAGgLAAg");
	this.shape_19.setTransform(98.6,53.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#ED2256").s().p("Ag+FCQgGAAgBgBQgDgCgKAAIibAAQgQAAgHgKIgDgDIAAivQAAgJADgEQABgBAAgIIAAhNQAAgGAFgCIAFgEQAMgHAKAAIAOAAIAOACIAIABQAFAAADACIAGAAIAMACQABABAGAAIAZAAQAPABAUgJQASgGAEgKIADgEIAEgIIADgMQABgIgBgFIAAgCQABgIgGgXQgDgJgGgGQgKgPgHgFQgFgFgCgGQgCgHgGgFIgpgpIgngoIgEgDQgEADgRAAQgFABgBgFQgCgFgEgFIgJgJIAAgBQgBgGACgGIADgMIACgGQgBgDACgFIACgIIAHgBQAWgDAIAAQAFgCAQAAIAFgBQAEgCAKAAQALAAAEgCIAGgBQAOAAAFgCQAEgCAKABQAJAAADgBQACgBAGAAIAJAAIAJgCIAMgBQAIAAADgCIAIgBIAJAAQAGAAADgCQACgBAHAAQAKAAADgCIADAAIADAAQAMAAAEgCIAMgBIALgCIAJgBIARgCIANAAIAKgCQAJgCAHACQAFAAAHAHIA1A1IAIAKQAGAIABACIAEAFQAEADAAADQADACAEAHQACAHAEACQACAIAHANIAIATQAEAHAAAGQABAGAEAKIAEAUIACAGIABACQgBAFACAIQACAIAAAEQgBAHACAGQABABAAAHIAAAeQAAAHACADQAEAFgEAHIgFAQQgCAHAAAJQAAAHgCACIgBABQABAHgEAMIgGAZIgNAmIgFANQgFAPgDAFQgDAEgCAIQgHAOgNATQgKARgRAQIgXAXIgIAGIgEAEQgIAHgQAKQgbASgVAGIgPAEQgLACgNAJQgJAFgCADIgIAEQgGACgFAAg");
	this.shape_20.setTransform(262.7,43.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#ED2256").s().p("AlUE6IgJgIQgFgFADgGQAGgLAFgFQgHgJAAgIQAAgEgDgCQgDgDgEACQgHADgVAAQgJgBgMAFQgJAEgIgEQgGgDgFACQgFADgKgEQgFgCgGAAIgdAAIgEgGIgDgDQgGgFADgGQACgDABgIIAEgLIADgOQABgJACgEIADgJIACgJIADgPIADgHIAFgSIAEgKIACgKQABgHADgEIAFgNQAHgPABgIIACgHIAAgEQADgGAAgIQACgDAAgHQABgHACgDQgBgCACgEIACgFIALgkIAKggIAJgcIABgEQADgDgCgIQgLgBgDgKIgCgCIgDgGQAAgBAEgEIAHgIQAGgHAIAEIAGABQAFgFACgLIADgMIACgEQABgDgCgCQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAgBAAgBIgBgFQgDgEAEgEQALgLAGgQIgCgEQgDgLAKgDIAIgDQAFgBADAAQAKACAHgEIAIAAQAMAAAEgCIAMgBQAJAAADgCIAHgBQAMAAADgCIAHAAIAJAAIAJgCIANgBIAPgCIAIgBIAIAAQAFAAADgCQADgCAIABQAJAAAFgBQADgCAJABQAJAAADgCIAHgBIAJAAQAGAAAEgCIAIgBIAIAAIAIgCIAMAAQAIAAAEgCIAIgBQABAGgCAFIgNAoIgCAJQgJAZgCAJQgCACAAAEIgCAFIgBAGIAFABIBMAAIAFgBQAMgEAPAEIAMAEQAIAFAKgFIADgCIAAgPQAAgNACgFQACgHgEgJQgIgRgBgJQgEgFgDgJQgDgLgDgEQgCgDgBgGIgCgKQACgBAHAAQAJAAAFgCQACgBAKAAQAJAAADgCIAIgBQAOAAAEgCIAIAAIAQgCIAOgBIAHAAQADAAADgCIAGgBIAKAAIAKgCIALAAQAIAAAEgCQADgCAHABQAMAAADgCIAIgBIARgCIANAAIAKgCIAKgBIAMgCQAEgCAIABQAFAAACAGIAKAjIACAJIgCAIQAIAIABAJIAAABQAGAIAGAUIABAFQAAAGAGAPQACADAAADIACANQACAHgBAGQAGAFAAABIAHAVIAGAVQAEAGADAOIAIAZIAJAeIAEAKIAFATIAGAOIACAJIADAIQADAFACAMIAIAcIABADQADAGAAADIgEAJIAGAGQAHAHAHASIAIAXIADAMIAFALQABADABAIIAKAfIAHAXIgFAGIgFAHIgHABQgFAAgDACIh+AAIgEgFIgCABQgFAFgIgBIg9AAQgGAAgEgCIgJgBIgxAAQgDgHgBgDIgFgRIgFgRIgNgoIgEgLIgDgJQgEgHgIgDIgcgIQgHgBgDABQgEACgKAAIgPAAQgGAAgDACIgIABIgiAAIgHAAQgFADgNAAIiGAAQgLAAgEABQgBABgGAAIgTAAQgMAWgGATIgBADQgDAEgCAJIgFANIgHARQgFAKgBAGIgEAIQgCAEgEAAIgMACQgIACgHgCIgMgCIgGgBQgKgEgHAFQgDACgFAAQgFABgCABQgBgBgFAAQgEAAgCgCIgHgDQgDABgCAEIgDAGIgHAIQgCACgGABQAAAAAAABQAAAAAAABQABAAAAABQABAAABAAIAJAFQAHAEAAAFQAAAAAAABQAAABAAAAQAAABAAAAQABAAAAAAQADAEgEAGQgHAKgMAAIgHgBg");
	this.shape_21.setTransform(178.5,49.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#ED2256").s().p("Al7F6IgCgCIgLgLIAAgNIAAmkQAAgMACgEIABiuQAAgKABgCIAFgBQAKgBgEgKIgEgIIACgCQACAAAHgBIAJgCQALABAHgDIALgBQAIAAADgCIAHAAIAMAAQAHAAAFgCIAJgBQAKAAADgCQADgBAGAAQANAAAEgCIAJAAIAIAAQAEgBADgBIAGgBQANgBACgCIALAAQALAAADgCQACgBAHAAQAMAAAEgCIACAAQAGgBACADQABACgBAGIAAACIAEABIDsAAQAMAAAEADIAHAAQABgEAAgSIAAgUIAGgEIALgCQAHgCAEAAQALABAEgCIAIgBIAJAAQAFAAAEgCIAKgBQAIAAAGgCQADgBAJAAQAJAAACgCIAIAAIAJAAQAGAAADgCIALgBIAIAAIAIgCIALgBIAOgCQACgBAIAAQAKAAAFgBQACgCAFABQANAAAEgCIAIgBIAIAAIABBVQAAAIABAEQABACAAAIIAABfQABANADADIAAAGIAABgQAAAGgCADQgBAAAAABQAAAAAAABQAAAAAAABQgBABAAAAIAAGSQABAGgFADIgIAFQgEADgFgCIgIAAIhGAAQgKAAgEABIgGABIh/AAIgBgBIgLgLIAAgPIAAgbQAAgJACgEIAAgKIAAlGQgCgCgHAAIhBAAQgMAAgEgCIgGgBIilAAIgHABIAAAFIAAAaQAAAIgCAEIgBAFIAAAXQACAFABAHIAAAOIAABKQgBAIACACIABAIIAABoIgBAFQgBAEAAAOIAAAgIgBAJQAAAFACAEIABACIgBAdIgHADIgGAGIgIABQgFAAgCACIgIABg");
	this.shape_22.setTransform(337.5,37.9);

	this.addChild(this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,376.9,81.5);


(lib.books = function() {
	this.initialize();

	// Calque 1
	this.instance = new lib.book1();
	this.instance.setTransform(66.3,8.8,0.664,0.664);

	this.instance_1 = new lib.book2();
	this.instance_1.setTransform(0,0,0.664,0.664);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,150,149.7);


(lib.slogan = function() {
	this.initialize();

	// Calque 1
	this.instance = new lib.jay_crownover();
	this.instance.setTransform(87.5,36.6,1,1,0,0,0,89.2,8.8);
	this.instance.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,10);

	this.instance_1 = new lib.nouvelle_serie();
	this.instance_1.setTransform(115.8,9.2,1,1,0,0,0,115.8,9.2);
	this.instance_1.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,8);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-7.7,-4,246.8,59.8);


(lib.btn = function() {
	this.initialize();

	// Calque 2
	this.instance = new lib.discover_bold();
	this.instance.setTransform(55.7,9.4,0.56,0.562,0,0,0,62.6,10.3);

	// Calque 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#51A5B6").s().rr(-68.2,-10.55,136.4,21.1,2);
	this.shape.setTransform(55.4,10.5,0.812,1);

	this.addChild(this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,110.8,21.1);


// stage content:
(lib.clash_728x90 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{loop_btn:174});

	// timeline functions:
	this.frame_196 = function() {
		this.gotoAndPlay('loop_btn');
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(196).call(this.frame_196).wait(1));

	// btn
	this.instance = new lib.btn();
	this.instance.setTransform(513.9,99.4,1,1,0,0,0,55.4,10.5);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(150).to({_off:false},0).to({y:69.6,alpha:1},14,cjs.Ease.get(1)).wait(10).to({scaleX:0.9,scaleY:0.9,x:511.2},11).to({scaleX:1,scaleY:1,x:513.9},11).wait(1));

	// books
	this.instance_1 = new lib.books();
	this.instance_1.setTransform(230,44.9,0.303,0.303,0,0,0,75,74.7);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(60).to({_off:false},0).wait(1).to({regY:74.8,scaleX:0.3,scaleY:0.3,alpha:0.002},0).wait(1).to({scaleX:0.31,scaleY:0.31,x:230.1,alpha:0.008},0).wait(1).to({scaleX:0.31,scaleY:0.31,x:230.3,alpha:0.019},0).wait(1).to({scaleX:0.31,scaleY:0.31,x:230.6,alpha:0.034},0).wait(1).to({scaleX:0.32,scaleY:0.32,x:231,alpha:0.053},0).wait(1).to({scaleX:0.32,scaleY:0.32,x:231.5,y:45,alpha:0.077},0).wait(1).to({scaleX:0.33,scaleY:0.33,x:232,alpha:0.105},0).wait(1).to({scaleX:0.34,scaleY:0.34,x:232.6,alpha:0.137},0).wait(1).to({scaleX:0.35,scaleY:0.35,x:233.3,y:45.1,alpha:0.174},0).wait(1).to({scaleX:0.36,scaleY:0.36,x:234.1,alpha:0.215},0).wait(1).to({scaleX:0.37,scaleY:0.37,x:234.9,y:45.2,alpha:0.26},0).wait(1).to({scaleX:0.39,scaleY:0.39,x:235.9,alpha:0.308},0).wait(1).to({scaleX:0.4,scaleY:0.4,x:236.8,y:45.3,alpha:0.359},0).wait(1).to({scaleX:0.42,scaleY:0.42,x:237.8,alpha:0.413},0).wait(1).to({scaleX:0.43,scaleY:0.43,x:238.9,y:45.4,alpha:0.469},0).wait(1).to({scaleX:0.45,scaleY:0.45,x:240,alpha:0.528},0).wait(1).to({scaleX:0.46,scaleY:0.46,x:241.2,y:45.5,alpha:0.588},0).wait(1).to({scaleX:0.48,scaleY:0.48,x:242.3,y:45.6,alpha:0.649},0).wait(1).to({scaleX:0.5,scaleY:0.5,x:243.5,alpha:0.712},0).wait(1).to({scaleX:0.51,scaleY:0.51,x:244.7,y:45.7,alpha:0.775},0).wait(1).to({scaleX:0.53,scaleY:0.53,x:245.9,alpha:0.838},0).wait(1).to({scaleX:0.55,scaleY:0.55,x:247,y:45.8,alpha:0.895},0).wait(1).to({scaleX:0.56,scaleY:0.56,x:247.8,alpha:0.937},0).wait(1).to({scaleX:0.56,scaleY:0.56,x:248.4,y:45.9,alpha:0.967},0).wait(1).to({scaleX:0.57,scaleY:0.57,x:248.7,alpha:0.986},0).wait(1).to({scaleX:0.57,scaleY:0.57,x:248.9,alpha:0.997},0).wait(1).to({regX:74.9,regY:74.9,scaleX:0.57,scaleY:0.57,x:249,alpha:1},0).to({regY:74.8,scaleX:0.55,scaleY:0.55,x:280.5,y:46.4},52).wait(1).to({regX:75,x:284,y:46.3},0).wait(1).to({x:288.2},0).wait(1).to({x:293},0).wait(1).to({scaleX:0.55,x:298.6},0).wait(1).to({x:304.9,y:46.2},0).wait(1).to({x:311.7},0).wait(1).to({scaleY:0.55,x:319.2},0).wait(1).to({x:327},0).wait(1).to({x:335.2,y:46.1},0).wait(1).to({x:343.7},0).wait(1).to({x:352.3,y:46},0).wait(1).to({x:361},0).wait(1).to({x:369.6,y:45.9},0).wait(1).to({x:375.4},0).wait(1).to({x:378},0).wait(1).to({regX:74.8,x:378.8},0).wait(42));

	// books text
	this.instance_2 = new lib.slogan();
	this.instance_2.setTransform(398.6,42.5,0.773,0.773,0,0,0,115.8,22.7);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(79).to({_off:false},0).to({scaleX:1,scaleY:1,x:458.7,y:44.5,alpha:1},38,cjs.Ease.get(0.5)).to({regY:22.6,scaleX:1.06,scaleY:1.06,x:470.6,y:45.4},22,cjs.Ease.get(-0.5)).wait(1).to({regX:114.3,regY:23.3,scaleX:1.05,scaleY:1.05,x:472,y:45.5},0).wait(1).to({scaleX:1.04,scaleY:1.04,x:475.6,y:44.9},0).wait(1).to({scaleX:1.03,scaleY:1.03,x:479.7,y:44.1},0).wait(1).to({scaleX:1.02,scaleY:1.01,x:484.4,y:43.2},0).wait(1).to({scaleX:1,scaleY:1,x:489.7,y:42.2},0).wait(1).to({scaleX:0.99,scaleY:0.98,x:495.4,y:41.2},0).wait(1).to({scaleX:0.97,scaleY:0.97,x:501.6,y:40},0).wait(1).to({scaleX:0.95,scaleY:0.95,x:508.1,y:38.8},0).wait(1).to({scaleX:0.93,scaleY:0.93,x:515,y:37.5},0).wait(1).to({scaleX:0.91,scaleY:0.91,x:522.1,y:36.2},0).wait(1).to({scaleX:0.89,scaleY:0.88,x:529.4,y:34.8},0).wait(1).to({scaleX:0.87,scaleY:0.86,x:536.8,y:33.5},0).wait(1).to({scaleX:0.85,scaleY:0.84,x:544.3,y:32.1},0).wait(1).to({scaleX:0.83,scaleY:0.82,x:551.4,y:30.7},0).wait(1).to({scaleX:0.82,scaleY:0.81,x:554.5,y:30.2},0).wait(1).to({regX:115.9,regY:22.6,scaleX:0.81,scaleY:0.81,x:556.3,y:29.5},0).wait(42));

	// clash_top
	this.instance_3 = new lib.clash_top();
	this.instance_3.setTransform(245.6,29.2,0.505,0.505,0,0,0,190.1,39.6);
	this.instance_3.alpha = 0;
	this.instance_3.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,8);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({x:299.6,y:34.2,alpha:1},17,cjs.Ease.get(-0.5)).to({regX:190,scaleX:0.5,scaleY:0.5,x:294.3},42).to({regX:190.1,scaleX:0.51,scaleY:0.51,x:275.6,y:14.2,alpha:0},14,cjs.Ease.get(1)).to({_off:true},1).wait(65).to({_off:false,regX:190,scaleX:0.39,scaleY:0.39,x:108.5,y:36.2},0).to({alpha:1},25,cjs.Ease.get(-0.5)).wait(33));

	// clash_bottom
	this.instance_4 = new lib.clash_bottom();
	this.instance_4.setTransform(335.4,71,0.505,0.505,0,0,0,188.5,40.5);
	this.instance_4.alpha = 0;
	this.instance_4.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,8);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({x:305.4,y:56,alpha:1},17,cjs.Ease.get(-0.5)).to({regY:40.6,scaleX:0.5,scaleY:0.5,x:309.9,y:55},42).to({regY:40.5,scaleX:0.51,scaleY:0.51,x:325.4,y:76,alpha:0},14,cjs.Ease.get(1)).to({_off:true},1).wait(65).to({_off:false,regX:188.4,regY:40.2,scaleX:0.39,scaleY:0.39,x:112.9,y:52.8},0).to({alpha:1},25,cjs.Ease.get(-0.5)).wait(33));

	// clash text
	this.instance_5 = new lib.clash_text();
	this.instance_5.setTransform(560.7,21.1,0.911,0.911,0,0,0,131.7,12.8);
	this.instance_5.alpha = 0;
	this.instance_5.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,8);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(15).to({_off:false},0).to({scaleX:1,scaleY:1,x:570.7,alpha:1},44,cjs.Ease.get(1)).to({_off:true},1).wait(79).to({_off:false,regY:12.7,scaleX:0.92,scaleY:0.91,x:338.4,y:23.2,alpha:0},0).to({alpha:1},25).wait(33));

	// logo
	this.instance_6 = new lib.logo();
	this.instance_6.setTransform(691.3,51.6,0.6,0.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(197));

	// bg
	this.instance_7 = new lib.background();

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(197));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(364,45,728,107.6);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;