(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 120,
	height: 600,
	fps: 24,
	color: "#666666",
	manifest: []
};



// symbols:



(lib.background = function() {
	this.spriteSheet = ss["clash_120x600_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.book1 = function() {
	this.spriteSheet = ss["clash_120x600_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.book2 = function() {
	this.spriteSheet = ss["clash_120x600_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.logo = function() {
	this.spriteSheet = ss["clash_120x600_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.nouvelle_serie = function() {
	this.initialize();

	// Calque 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAAHEIAAh3IA8AAIAAAUIgnAAIAAAaIAmAAIAAAUIgmAAIAAAgIAnAAIAAAVgAhlHEIAAh3IAhAAQAMAAALAFQAKAEAIAIQAIAIAEALQAEALAAAMQAAANgEALQgEAKgIAIQgIAIgLAFQgKAFgMAAgAhOGvIAEAAQAUAAAKgKQAJgKAAgTQAAgngnAAIgEAAgAIHBZQgOgGgMgMQgKgMgGgPQgGgQAAgRQAAgPAGgQQAGgPAKgMQALgNAPgHQAPgHARAAQATAAASAKIAAAmQgHgIgKgFQgJgEgKAAQgLAAgJAFQgJAEgHAIQgGAIgDAKQgDAIAAALQAAAKADAKQADAKAHAHQAGAJAJAEQAJAFALAAQAJAAAKgFQAJgFAIgIIAAAmQgKAFgJACQgJADgKAAQgQAAgPgHgAFdBZQgPgGgKgMQgLgMgFgPQgGgQAAgSQAAgQAGgQQAGgPAKgMQAKgMAPgGQAPgHASAAQASAAAPAHQAPAGALAMQAKAMAGAPQAGAQAAAQQAAASgGAQQgGAPgKAMQgLAMgPAGQgPAHgSAAQgSAAgPgHgAFrgmQgJAEgHAIQgGAHgDAKQgEAJAAAJQAAAJADALQADAJAFAJQAGAHAJAGQAKAFAMAAQANAAAJgFQAKgGAFgHQAGgJACgJQADgLAAgJQAAgJgDgJQgDgKgHgHQgGgIgJgEQgJgEgLAAQgKAAgJAEgABLBZQgPgGgLgMQgLgMgGgPQgFgQAAgRQAAgPAFgQQAGgPALgMQALgNAOgHQAPgHASAAQATAAARAKIAAAmQgGgIgKgFQgKgEgKAAQgLAAgJAFQgJAEgGAIQgGAIgDAKQgEAIAAALQAAAKAEAKQADAKAGAHQAGAJAJAEQAJAFALAAQAKAAAJgFQAKgFAHgIIAAAmQgJAFgJACQgJADgKAAQgQAAgPgHgAn/BXQgHgFgHgIIgFgHIgCgDIAVgUQADAKAIAHQAIAHAKAAQAJAAAGgHQAGgHAAgKQAAgFgCgEQgDgFgDgDIgIgEIgKgEIgDgBIgPgHIgKgJQgGgEgCgGIgCgIIgBgJIABgHQABgGACgGQAEgJAGgGQAGgHAJgEQAJgEAKAAQALAAANAGQANAEAHAJIgPAVQgFgGgGgDQgFgEgIAAQgIAAgGAGQgGAFAAAIQAAAHAGAEQAGAFAMAFIAQAHQAGACAGAFQAGAFADAJQAEAIAAALQAAAZgPAQQgOAPgZAAQgQAAgNgJgAD+BcIAAhJIg7AAIAABJIgfAAIAAihIAfAAIAABAIA7AAIAAhAIAgAAIAAChgAiDBcIAAihIBUAAIAAAcIg1AAIAAAjIAzAAIAAAaIgzAAIAAAsIA1AAIAAAcgAi6BcIAAihIAfAAIAAChgAjrBcIgohCIAAAAIAABCIggAAIAAihIArAAQAaAAAOAMQAPALAAAaQAAAQgJAMQgJAMgQADIAuBFgAkTAEIAEAAQAOAAAIgEQAIgFAAgOQAAgPgIgEQgHgFgPAAIgEAAgAmcBcIAAihIBUAAIAAAcIg1AAIAAAjIAzAAIAAAaIgzAAIAAAsIA1AAIAAAcgAmFhWIAaglIAWAOIghAggAC2kXIg/inIAiAAIAnBtIABAAIAkhtIAiAAIg/CngAAXkcQgLgFgIgKQgFgJgDgMQgEgNAAgQIAAhhIAeAAIAABbIABARQABAJACAGQADAHAGAFQAGAEAKAAQAJAAAGgEQAGgFADgHQADgGAAgJQACgIAAgJIAAhbIAfAAIAABhQAAAQgDANQgEAMgHAKQgHAJgMAFQgMAFgPAAQgQAAgMgFgAiIkeQgQgGgKgMQgLgMgFgPQgGgQAAgSQAAgSAGgPQAGgQAKgMQALgLAPgHQAPgHASAAQASAAAOAHQAPAHALALQALAMAGAQQAFAPAAASQAAASgFAQQgGAPgKAMQgLAMgPAGQgPAHgSAAQgSAAgPgHgAh7mfQgJAFgHAHQgGAIgDAJQgDAKAAAKQAAAKADAKQACAJAGAJQAGAIAJAFQAJAFANAAQAMAAAJgFQAKgFAFgIQAGgJADgJQACgKAAgKQAAgKgDgKQgDgJgGgIQgGgHgJgFQgJgEgLAAQgLAAgJAEgAjekYIhWhyIAAAAIAABvIggAAIAAioIAXAAIBWByIAAhtIAgAAIAACmgAIokbIAAijIBUAAIAAAcIg1AAIAAAjIAzAAIAAAcIgzAAIAAAsIA1AAIAAAcgAHRkbIAAijIAfAAIAACHIAtAAIAAAcgAF6kbIAAijIAfAAIAACHIAtAAIAAAcgAEQkbIAAijIBUAAIAAAcIg1AAIAAAjIAzAAIAAAcIgzAAIAAAsIA1AAIAAAcgAm+kbIgMgiIg5AAIgNAiIhrAAIAAijIAfAAIAACHIAtAAIAAAUIA9igIAZAAIA9CogAnTlYIgUg7IgBAAIgSA7IAnAAg");
	this.shape.setTransform(53,41.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-10.6,-3.4,127.3,90.5);


(lib.jay_crownover = function() {
	this.initialize();

	// Calque 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#ED2256").s().p("AJEBXIg/ipIAiAAIAoBuIABAAIAlhuIAiAAIhACpgAGQBQQgPgHgLgMQgLgMgGgQQgFgPAAgSQAAgRAGgQQAFgQALgMQALgMAPgGQAQgHASAAQASAAAPAHQAPAGALAMQALAMAGAQQAGAQAAARQAAASgGAPQgGAQgKAMQgLAMgPAHQgQAHgSAAQgTAAgPgHgAGegxQgKAEgGAIQgGAIgEAJQgDAKAAAKQAAAIADAKQACAKAGAIQAGAJAKAFQAJAFANAAQANAAAJgFQAJgFAGgJQAGgIADgKQACgKAAgIQAAgKgDgKQgDgJgHgIQgGgIgJgEQgJgFgLAAQgLAAgJAFgAiYBQQgPgHgLgMQgLgMgGgQQgFgPAAgSQAAgRAGgQQAFgQALgMQALgMAPgGQAQgHASAAQASAAAPAHQAPAGALAMQALAMAGAQQAGAQAAARQAAASgGAPQgGAQgKAMQgLAMgPAHQgQAHgSAAQgTAAgPgHgAiKgxQgKAEgGAIQgGAIgEAJQgDAKAAAKQAAAIADAKQACAKAGAIQAGAJAKAFQAJAFANAAQANAAAJgFQAJgFAGgJQAGgIADgKQACgKAAgIQAAgKgDgKQgDgJgHgIQgGgIgJgEQgJgFgLAAQgLAAgJAFgAmWBQQgPgHgLgMQgLgMgGgQQgGgPAAgRQAAgQAGgQQAGgQALgMQALgMAPgIQAPgHASAAQATAAASAKIAAAnQgHgJgKgFQgKgEgKAAQgLAAgJAFQgKAEgGAJQgGAHgEALQgDAKAAAJQAAALAEAKQADAKAGAIQAHAIAJAEQAJAFALAAQAKAAAKgFQAJgFAIgHIAAAmQgKAFgKACQgJADgJAAQgRAAgPgHgAtrBSQgJgEgHgHIAVgXQABAEAEADQAEADAEABQAEAAADgEQADgDABgEIACgMIAAgPIAAhnIAhAAIAABsQAAAPgCAJQgCAJgGAJQgGAKgKAEQgKAFgLAAQgJAAgIgFgAE5BWIhYhyIAABuIggAAIAAioIAXAAIBXByIABAAIAAhuIAgAAIAACogABoBWIghhqIgBAAIgfBqIgYAAIgyioIAhAAIAgBwIAAAAIAhhxIAUAAIAiBxIAAAAIAhhwIAiAAIg4CogANVBSIgphDIAABDIggAAIAAikIArAAQAaABAPAMQAPAMAAAaQAAARgJANQgJALgQADIAvBFgAMsgFIAEAAQAPAAAIgFQAHgHAAgNQAAgPgHgFQgIgFgPAAIgEAAgAKgBSIAAikIBWAAIAAAdIg1AAIAAAkIAzAAIAAAaIgzAAIAAAtIA1AAIAAAcgAjyBSIgphDIAABDIggAAIAAikIArAAQAaABAPAMQAPAMAAAaQAAARgJANQgJALgQADIAvBFgAkbgFIAEAAQAPAAAIgFQAHgHAAgNQAAgPgHgFQgIgFgPAAIgEAAgApcBSIAAhMIgzhYIAlAAIAdA6IAgg6IAmAAIg1BYIAABMgAqsBSIgNgiIg5AAIgOAiIgiAAIBAioIAaAAIA+CogArCAVIgVg6IgSA6IAnAAg");
	this.shape.setTransform(89.2,8.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,178.5,17.5);


(lib.discover_bold = function() {
	this.initialize();

	// Calque 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJBYQgRgQAAgbIAAhjIAgAAIAABeQAAASAHAIQAHAJARAAQAQAAAIgJQAHgIAAgSIAAheIAhAAIAABjQAAASgHANQgIANgPAHQgPAHgUAAQgeAAgPgPgAi7BSQgTgVAAgnQAAglATgVQATgUAlAAQAkgBATAWQATAUAAAmQAAAmgTAVQgUAVgkAAQgkAAgTgVgAihgQQgLAOAAAZQAAAZAKAOQAKANAUAAQAoAAAAg0QAAg0gnAAQgUAAgKANgAlIBSQgSgVAAgmQAAgXAIgSQAJgTARgJQARgKAWAAQAXgBAXAMIgLAbQgIgFgJgCQgJgDgJAAQgTAAgKANQgKAOAAAYQAAA0AnAAQARABAXgJIAAAcQgTAIgYAAQgiAAgSgVgAJOBlIgmg8IgSAAIAAA8IghAAIAAibIAuAAQAgAAAPALQAQANAAAXQAAAMgIALQgIAKgOAHIAuBEgAIWAOIALAAQAQgBAHgEQAIgGAAgJQAAgMgIgEQgHgFgRAAIgKAAgAGsBlIAAibIAhAAIAACbgAF0BlIgmg8IgSAAIAAA8IghAAIAAibIAuAAQAgAAAPALQAQANAAAXQAAAMgIALQgIAKgOAHIAuBEgAE8AOIALAAQAQgBAHgEQAIgGAAgJQAAgMgIgEQgHgFgRAAIgKAAgACuBlIg2ibIAiAAIAdBbIAGATIADAQQABgKAHgZIAehbIAhAAIg1CbgAnOBlIAAibIBaAAIAAAbIg5AAIAAAhIA1AAIAAAbIg1AAIAAAoIA5AAIAAAcgApxBlIAAibIAxAAQAmAAAWAUQAVAVAAAiQAAAngWAUQgWAVgqAAgApQBJIAOAAQAwABAAg0QAAgxgsAAIgSAAgAm1hDIAAgDQATgVAHgLIAkAAIAAADIgTAQIgVAQg");
	this.shape.setTransform(62.7,10.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,125.4,20.7);


(lib.clash_top = function() {
	this.initialize();

	// Calque 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#ED2256").s().p("AgLALIgFgJQAIgCADgBIAFgJIARABIgCAEQgEAFgCAHIgGAAIgIADIgEABg");
	this.shape.setTransform(251.2,22.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#ED2256").s().p("AgOASQgCgCgEgFIADgCQAHgFABgDIACgKIAAgLIABgCQAMACAPgCIgWAtIgNgFg");
	this.shape_1.setTransform(255.9,23.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#ED2256").s().p("AAAAOIgJgDQgBgFgCgDQgEgEAGgHIAEgFIAFAAQAIgEAHAKQAAAHgHALQgBAEgEAAIgCgBg");
	this.shape_2.setTransform(146,52.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#ED2256").s().p("AAAAbQAAgCAAgFIAAgHIgEgCQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQgBAAgBgBIgHgDIAAgEIAJgWQADgCAEACQADACACAAIAEAIQAFAGgDAHIABACQAEADAAAHIABAMIgKAGIgDABIgEgBg");
	this.shape_3.setTransform(142,58.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#ED2256").s().p("AiCCtIAAg8QACgFAAgNIABkLIACgDIAKgKIAPgBIDEAAQAOABAEACIAHAAIAJAKIAABuQABAKgDADIAAAJIAADBQgBAHgHAAIgIAAIgHABQgDAAgDABQgCABgGAAIgKAAQgHAAgDADIgIAAQgNAAgDACIgLABQgKAAgEABIgKABIgHAAQgFAAgBACIgHABQgNAAgEACIgJABQgJAAgEABIgGABQgPABgFACIgHAAIgQACIgLABQgMAAgDACIgDAAQgEgEgBgJg");
	this.shape_4.setTransform(367.1,21.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#ED2256").s().p("AhzDQIgGgPQgHgTACgSQACgDAAgIQABgHABgFIAAgGIACgFQADgDABgEIABgHIAAgIIgIgHQgFgFADgFQAFgKgEgMQgCgKAAgPIAAiNQgBgLgCgDIgBgFIAAhFQAIgFgCgHQAHgGAKAAIA8AAIAJAAQAGABAEACQAEACADgDQAEgCAHAAIARAAQAHABAEgCIAFgBIBfAAIAMAMIABAQIAAFuQgCAFgEAAIgRADQgKACgGgBIgDAAQgCACgNAAIgRACIgEABIgFgBIgOADIgLABIgOACQAAABgHAAQgLAAgGABIgKABQgJAAgDACIgKAAIgNADQgBABgHAAIgSABIgMABQgJAAgDADQgEgBgBgFg");
	this.shape_5.setTransform(314.3,24.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#ED2256").s().p("AiIFYIAAgLIAAgVQAAgEABgHQACgIAAgDIABgLIACgKQACgDABgHQABgHACgDIAIgBQAIAAADgBQACgCAGABQAJAAACgBQgBgLgJgEIgKgFQAAgRgLgHIgJABQgGgIABgIIABgEQADgDgBgEIgDgGQgHgSAEgKIABgFQAAgJAFgKQgEgEABgHQAAgOgCgFIAAgJIAAidQAAgJgCgFIgBgKIAAifIAAgJQAAgFgDgDIAAgEIAAg6IAMgNIAfAAIAEABQADACAMAAIAqAAQANAAADADIAKAAQAGAAADgBQACgCAGAAIAuAAQAIAAADgCIAHgBIAyAAQAHABAEAEQAEAEABAHIAAEJQAAAMgCAFIgBAHIAADRQAAAHACADIABAKIAABTQAAAJACACIgDAFQACASgDAIIgBAIIgBALQgUAFgLgBIgDAAQgFACgQAAIgEAAQgEADgGAAIgLAAQgHAAgDACQgBABgIAAIgRACIgNAAIgIACIgKABIgIAAQgFABgDACIgHAAQgNAAgFACIgMABQgIAAgDABQgCABgHAAIgIABQgFAAgEACIgKAAIgHABQgEAAgDABIgHABQgCgEAAgHg");
	this.shape_6.setTransform(84.8,36.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#ED2256").s().p("AjREHIgBgDQAAgDgDgCQgIgEgFgKQgKgVgGgTIgBgJQgBgKgBgDQgBgBAAgNQAAgIADgDQgFgJgBgJIgCgKIAAgLIgBgEQgCgCAAgEIAAgHIAAgXQAAgKACgDIABgIIAAgKQAAgGACgEIAAgHIABgHQACgCAAgHQAAgJACgCIABAAIACgUQAAgGADgFQADgDAAgIQgBgJAGgEQAHgFABgKQAEgLABgGQABgIAKgOQAJgOAEgCIADgCQAKgFAAgKIAHgMIAZgYQALgLANgCQAFgBABgEQACgGAJgFIAQgKIAQgIIAGgBQADAAAKgEIAEgCQADAAAGgBQAFgCADAAQAFABAEgDQAAAAABAAQAAAAABAAQABAAAAAAQABAAAAAAQAGAEAEgGQAEgEAIAAQAJABAFgEQACgBAFACIANAEQAKgOACgFIAMAFQAIAEADAFQAFgDADgEIAEgGQAFgFAGADIAMAFIgBAGIACABQAIgGALAIQAFAEAFAAIADAAIAFACQADABADgBIAKgEIALAKIALABIAYACIAFABQAJAEAGgFQAFgEAGACIALADQABAAAAABQABAAAAABQABAAAAABQAAAAAAABIAAAGIAAAbQAAAMgCAEIAAAJIAABTIgBAMIAGAHIAAA9QAAAIACADQABABAAAEIAAAdIgJAKIgOAAIgCgDQgBgBAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAIgDACIgBAAIgxgSQgHABgSgGIgOgEQAAgIgJgEIgKgHIgBgDQgDABgDALIgJABQgCAIgDACIgNAOIgHAGQgKAEACAKIgBAEQgPALgMgBQAAADACACIADADQADAEAAACQgBAFAGALIACACQAEAHgHADIgIAFIgDAGQADADAGABQAHACACABIABAMQASAVAFAFIAcAcQALALAFADIAHAGIAGAHIgBACQgHgBgMACQgNACgHgBIgDAAQgDADgQAAIgJACQgBABgFAAIgKABQgGgBgFACIgKAAIgNACIgKABIgHAAQgDABgDACIgDABIgFAAQgMAAgFABIgKABQgKAAgEACIgIAAIgKABQgGAAgEACIgLABQgIAAgEABQgCABgJAAQgLAAgDACIgGABQgNAAgEACIgEABIgFAAIgPACIgMAAIgMACQgBABgEAAIgDAAgAhUCQQgCAFgIAHQgCADACACIAHgGQAEgEAEgBIAAgFIgDgCIgCABgAgqCOIAAACIABABIADgCIgBgCIgDABgAABCAIADAIIAHACQgCgCABgGQABgEgDgBgAhyAYQAAAAAAABQgBAAAAABQAAAAABABQAAABAAAAIAEACIACgDIADgHIgDAAQgDAAgDAEgAhdgwIAAALIgBAMQgBADgHAFIgDACQADAFADACIANAFIAYgwQgPACgPgBgAiJgqQgDADgIADIAFAJIACAAIAEgBIAKgEIAGAAQACgIAEgFIACgFIgSgBg");
	this.shape_7.setTransform(264.4,26.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#ED2256").s().p("AkIGIIgKgBQgGgIgEgQIgCgGQgBgEAAgDIgCgDIgDgQIgDgLIgBgFQAAgDgCgCIAAgHIgCgMIAAgIIAAgLQgBgGgCgEIAAgFQAAgKgDgDIgBgFIgCgPIAAh7IABgJIABgKIAAgGQABgEACgCIABgCIABgMIABgLQAEgMgBgGQAGgLAAgNIABgDQAFgMACgOIAFgOIADgJQAAgGACgDIAFgPQACgJAEgFQACgCABgGQADgQALgRIACgGIAPgYIACgEIAMgTQAJgKADgHQAEgDAGgIIAKgMQAFgGABgCQAAgBAAAAQAAAAABgBQAAAAAAgBQABAAABAAIAIgKIAEgGIAGgFQADgDABgEIADgDQAIgIADgGQAEgFAEgCIALgJQAHgIAEgBQAEgCAIgHIAOgKQAJgGAGgCQADgEAJgEQAIgEAEgDIAQgIQAJgFAHgCIACgBQAJgFAXgIIATgGIAegIIAOgCQAFAAAEgCQABgBAFAAIANAAIAFAAQAFgDAIAAIAOAAIACABQAFADAGAAIAMgBIALAAIAEABQAEACAIAAIAMAAQAIAAADACQAEABAHAAQAKAAAEACQACABAHAAQAJAAADACIAEAAQAFgBAJACIAQACIABAIIAAAIQAAAFABADIABAIIAAAuQAAAQACAFIAAAIIAAA1QAAAIADADIABAGQABAqgBArIgBAEQgDADAAAKQAAANgCAGIAAAPQAAAIgGACIgEACIgIADQgCAAgGgDIgVgIIgNgDQgIgCgFgDQgDABgGgCIgJgCIgSgEIgIgBIgHAAQgDgBgDgCIgXAAIgCABQgDAEgJAAIgFAAQgFgBgHACIgMADQgGABgLAGIgQAJIgLAJIgPANQgJAHgGAGIgRATIgNASIgIASIgGAOIgEAMIgIASIgGAOQgBALgBADQAAAFgBAKQgCAKABAFQAAAJgDADIgBAJQAAAFACAEIACADQgBAHADAOIACAMQABAIACAEIADAMQABAKAEAHQABABAAAFQABAEABACQADANAIAZQADAHADAGIAgAgIAHAFIAIAGQgHAFgDAAIgOAAQgHAAgDACIgJABIgHAAQgEAAgEACIgKABQgKAAgEABIgMABQgJAAgDACQgCABgJAAIgHAAQgEAAgDACQgCABgHAAIgIAAQgFAAgDACIgLAAQgKAAgDACIgKABQgLAAgEACIgEABIgEAAIgRACIgKAAQgMABgCACIgIAAIgIAAQgGABgDACIgGAAQgMAAgHACIgGABIgEAAg");
	this.shape_8.setTransform(31.1,40);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#ED2256").s().p("AlTEyIgBgBQAIgQACgIQADgMgEgHQgDgDADgDQAFgFAGgSIAMgnQADgJADgLQABgEACgBQADgDACgFIAFgIQABgBAAgFQAAgLACgDQAAgBAAAAQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgIADgHIAIgaIAMgkQAFgKAAgGQACgDABgGIAEgKIAJgaQAEgSAEgIQAGgWAFgJIABgKIAJgZIAEgQIAGgUIAFgNQADgIAAgGIABgDQAGgPADgTIADgIIAFgSQADgFACgKIAEgQQAEgGgBgFQAAgCABgEIACgGQAAgFADgEQABgEABgGQAAgGAHAAIEwAAQAHAAABABQABABADAGIAIAZIAGASIAZBJIAGASIAMAlIAEAOQABAIAEAHQAFALAHAZIAMAlIAIAYIAIAXIAGAPQACAJADAFQAAAHAFALIANAqIANAlIAMAkQACAEABAKQAGANADAPIADAFQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAIgEAAQgNAAgDACIgHABIgJAAQgGAAgDACIgMAAIgLACQgBABgIAAIgIABQgFAAgEACQgCABgDgBIgFAAQgKAAgEACIgMABQgJAAgDACIgHAAIgJABQgHAAgDACIgEABIgEgBIgIABQgFAAgDABIgLABQgKAAgEACIgDABIgGAAIgHAAQgFAAgDACIgHABQgOAAgEABIgIABIgIAAQAAgEgDgGIgEgJIgDgKIgFgJQgFgMgBgHIgHgSIgPgmQgEABAAAFIgGASQgCAJgCAKIgKAeIgDAOIgJAcIgCAFQgDAEgEAAQgKgBgJADIgJABQgKAAgDACIgEABIgFgBIgIAAQgFABgDACIgHAAIgSACIgNABQgGAAgFACIgJABQgMAAgFACIgDABIgGgBIgOACIgNABIgMACQgBABgIAAIgMACQgCABgFAAIgTACIgNAAQgHAAgEACIgHABIgLAAQgGAAgEADg");
	this.shape_9.setTransform(180.4,32.6);

	this.addChild(this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,380.2,79.2);


(lib.clash_text = function() {
	this.initialize();

	// Calque 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHfFOQgEgFAAgGQAAgGAEgFQAEgEAHAAQAGAAAFAEQAEAFAAAGQAAAGgEAFQgFAEgGAAQgHAAgEgEgAGDFOQgIgEgGgHQgGgIgDgKQgDgKAAgMIAAhMIAZAAIAABHIABAOIADAMQACAFAFAEQAFADAHAAQAIAAAEgDQAFgEACgFQACgGABgGIAAgOIAAhHIAaAAIAABMQgBAMgCAKQgDAKgFAIQgGAHgJAEQgJAEgNAAQgMAAgKgEgAEEFNQgMgFgHgKQgJgJgFgMQgEgMAAgOQAAgPAEgMQAFgMAJgJQAIgKALgFQANgFANAAQAOAAANAFQALAFAIAJQAJAKAFAMQAEAMAAAPQAAAOgEAMQgFAMgJAJQgHAKgMAFQgMAFgPAAQgOAAgMgFgAEPDnQgHAEgFAGQgFAGgDAHQgCAIAAAIQAAAHACAIQACAIAFAGQAEAHAHAEQAIAEAJAAQAKAAAIgEQAHgEAEgHQAFgGACgIQACgIAAgHQAAgIgCgIQgDgHgFgGQgFgGgHgEQgHgDgJAAQgIAAgHADgAhOFOQgJgEgGgHQgFgIgDgKQgDgKAAgMIAAhMIAZAAIAABHIAAAOIAEAMQACAFAEAEQAFADAIAAQAHAAAEgDQAFgEADgFQACgGAAgGIABgOIAAhHIAZAAIAABMQAAAMgCAKQgEAKgFAIQgFAHgKAEQgJAEgMAAQgNAAgJgEgAjNFNQgMgFgIgKQgJgJgEgMQgEgMgBgOQABgPAEgMQAEgMAJgJQAJgKALgFQAMgFAOAAQAOAAAMAFQALAFAJAJQAIAKAFAMQAEAMAAAPQAAAOgEAMQgFAMgIAJQgIAKgMAFQgLAFgPAAQgPAAgLgFgAjDDnQgHAEgFAGQgEAGgDAHQgDAIABAIQAAAHABAIQACAIAFAGQAFAHAHAEQAHAEAKAAQAKAAAHgEQAHgEAFgHQAEgGADgIQABgIAAgHQABgIgDgIQgDgHgFgGQgFgGgGgEQgIgDgIAAQgIAAgIADgAlBFQIgchRIAAAAIgLBQIgaAAIAWiEIARAAIAgBVIAehVIASAAIAUCEIgZAAIgKhQIgBAAIgdBRgACXFPIAAiAIA/AAIAAAVIgmAAIAAAdIAkAAIAAAVIgkAAIAAA5gAA/FPIgfg0IAAAAIAAA0IgZAAIAAiAIAiAAQATAAAMAJQAMAJgBAUQAAANgGAKQgIALgMACIAlA2gAAgEKIADAAQALAAAGgFQAGgEABgLQgBgLgGgEQgGgEgLAAIgDAAgAmdFPIgJgbIgtAAIgKAbIgbAAIAyiEIAUAAIAwCEgAmuEfIgQguIAAAAIgOAuIAeAAgAEWA/QgEgFAAgGQAAgGAEgFQAFgEAGAAQAGAAAFAEQAEAFAAAGQAAAGgEAFQgFAEgGAAQgGAAgFgEgAArA+QgMgFgIgKQgIgJgFgMQgFgMABgOQgBgNAFgMQAFgMAIgJQAJgKALgFQAMgFAOAAQAOAAAMAFQAMAFAIAJQAJAKAEAMQAEAMABANQgBAOgEAMQgEAMgJAJQgIAKgMAFQgMAFgOAAQgPAAgLgFgAA1gmQgGAEgFAGQgFAGgDAHQgCAIAAAHQAAAGACAIQACAIAEAGQAEAHAIAEQAHAEAKAAQAKAAAHgEQAHgEAFgHQAFgGACgIQABgIAAgGQAAgHgCgIQgDgHgEgGQgFgGgHgEQgIgDgIAAQgIAAgIADgAhAA9QgKgHgHgMIAQgQQADAIAGAGQAHAFAHAAQAHAAAFgFQAEgGAAgHQABgFgCgDIgFgGIgFgDIgIgEIgCAAIgNgGQgFgBgDgEQgEgEgCgGQgCgFAAgHQAAgIADgHQACgHAGgGQAEgFAHgDQAIgDAHAAQAJAAALAEQAKAEAGAGIgNASQgDgFgFgDQgFgDgGAAQgGAAgEAEQgFAFgBAGQABAGAFADIANAIIANAFIAKAHQAEADADAGQACAGAAAJQAAAUgLAMQgLAMgUAAQgNAAgJgGgADuBCIhEhXIgBAAIAABVIgZAAIAAiCIASAAIBEBYIABAAIAAhUIAZAAIAACAgAh3BAIAAh+IAZAAIAAB+gAieBAIgeg0IgBAAIAAA0IgZAAIAAh+IAiAAQAUAAALAJQAMAJAAAUQAAANgHAKQgHAJgMACIAkA2gAi9gDIADAAQAMAAAGgFQAGgEAAgLQAAgLgGgEQgGgEgMAAIgDAAgAkwBAIAAh+IAiAAQAVAAAMAJQAMAJAAAVQAAAUgLAJQgLAKgUAAIgMAAIAAAwgAkXgDIAGAAQALAAAFgEQAGgEAAgMQAAgLgGgEQgGgEgMAAIgEAAgAFljPQgFgEAAgHQAAgGAFgEQAEgFAGAAQAGAAAFAFQAFAEAAAGQAAAHgFAEQgFAFgGAAQgGAAgEgFgADGjQQgLgFgIgJQgJgKgFgMQgEgMAAgNQAAgNAEgNQAEgMAKgKQAIgJALgGQAMgFAOAAQAPAAANAHIAAAeQgFgGgHgEQgIgDgIAAQgIAAgIADQgHAEgFAGQgEAGgDAIQgDAIABAJQgBAIADAIQADAHAEAGQAFAHAHADQAIAEAIAAQAIAAAIgEQAHgEAFgGIAAAeIgOAGQgIACgHAAQgNAAgMgGgAjWjPQgLgGgIgJQgJgJgEgNQgFgMAAgOQAAgOAFgNQAEgMAJgJQAIgJALgFQAMgFAOAAQAOAAAMAFQAMAFAIAJQAJAJAFAMQAEANAAAOQAAAOgEAMQgFANgJAJQgHAJgNAGQgLAFgPAAQgOAAgMgFgAjLk1QgHADgFAGQgFAGgDAIQgCAHAAAIQAAAIACAIQACAHAFAHQAEAGAHAEQAHAEAKAAQAKAAAHgEQAIgEAEgGQAFgHACgHQACgIAAgIQAAgIgDgHQgCgIgFgGQgFgGgHgDQgHgEgJAAQgIAAgHAEgAlnjKIgwiEIAbAAIAeBWIAAAAIAdhWIAbAAIgyCEgACDjLIhEhaIgBAAIAABXIgZAAIAAiDIASAAIBEBZIABAAIAAhWIAZAAIAACDgAENjOIAAiAIBCAAIAAAWIgpAAIAAAcIAnAAIAAAWIgnAAIAAAjIApAAIAAAVgAgsjOIAAiAIBBAAIAAAWIgnAAIAAAcIAlAAIAAAWIglAAIAAAjIAnAAIAAAVgAhwjOIAAiAIAZAAIAABrIAjAAIAAAVgAkgjOIAAiAIAZAAIAACAg");
	this.shape.setTransform(45.1,39.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-5.4,5.9,101.1,67.8);


(lib.clash_bottom = function() {
	this.initialize();

	// Calque 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#ED2256").s().p("AAAACIAAgDIAAAAIABADg");
	this.shape.setTransform(36.2,53.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#ED2256").s().p("AgBAAIADgCQABACgBADg");
	this.shape_1.setTransform(43.3,60);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#ED2256").s().p("AgBAAIABAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIABABIgCACg");
	this.shape_2.setTransform(53.6,59.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#ED2256").s().p("AAAgBIABACQAAAAAAAAQAAAAgBAAQAAABAAAAQAAAAAAAAg");
	this.shape_3.setTransform(43.7,59.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#ED2256").s().p("AAAACQAAAAAAAAQAAAAAAAAQAAgBAAAAQgBAAAAgBIABgBIACABQAAAAAAABQAAAAAAABQgBAAAAAAQAAAAAAAAIgBAAg");
	this.shape_4.setTransform(37.4,62);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#ED2256").s().p("AgBAAQgBAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAgBAAAAQAAAAAAAAQAAAAAAABIADABIgDABQAAAAAAAAQAAgBAAAAQAAAAAAAAQgBgBAAAAg");
	this.shape_5.setTransform(34.6,57.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#ED2256").s().p("AAAAAQAAgDgCgCIACgBQAGAGgFAGIgBABQAAgCAAgFg");
	this.shape_6.setTransform(37.6,48.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#ED2256").s().p("AgDgCQADgDAEAFIgDAEg");
	this.shape_7.setTransform(47.5,60.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#ED2256").s().p("AgEADQACgDACgCQAEgCABAEIgFADIAAAAIgEAAg");
	this.shape_8.setTransform(49.3,59.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#ED2256").s().p("AgEADIAAgBIAAgBIAFgFIADABIABABIgBACIgEAEIgBABIgDgCg");
	this.shape_9.setTransform(36.1,51.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#ED2256").s().p("AgCACIgFgBQACgBAFgBQADgCACgDIADAHIgGAGg");
	this.shape_10.setTransform(39.5,64.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#ED2256").s().p("AgKAIQgCgDABgFIALgCQAFgCACgCQACgCADABIAAAAIgKAPQgGgDgGADg");
	this.shape_11.setTransform(37.9,55.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#ED2256").s().p("AgJAAQgBAAABgDQABgDACgCQABAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAIANAHIgLAKg");
	this.shape_12.setTransform(53.5,48.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#ED2256").s().p("AAHAcIgBgDIgCgOIAAgHIgBgIIgHgFQgDgBgCgEQgEgGAFgEIAGgFQACACAAAEQgBAKAGACIADALIADAKQABACgBAFIgCAEIAAADIACAHIgEgDg");
	this.shape_13.setTransform(50.1,52.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#ED2256").s().p("AgbAVQAFgJgDgHQgCgCgGABQgGAAgDgEQACgEAFgBQABgBAAABQABAAABAAQAAAAABAAQAAABABAAIADADIATgCIAEgMIAFAKIAFAAQAGABADgHIAGgHIAIgBIAIgCIAGABQgFACgFAFIgKAHQgFADADADQAEAGgEAEIgFAEQgDACgDgCQgCgCgFAAQgDAAgBgCQgBgBAAAAQAAAAAAAAQgBAAAAAAQAAAAAAABQgDACgEAAIgIAAIgDAIQAAABAAAAQgBABAAAAQgBAAAAAAQAAAAgBAAIgDgBg");
	this.shape_14.setTransform(48.2,63.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#ED2256").s().p("AgdAxIABgCQAEgEAAgEIABgHIgJgNIgGgEIADgHIAUgFIAEgJIgHgNIgOgFIgCAGIgBgGQAAgFgCgCIAFgLIAGgJQACgEAEAAQAEAAABAFIgKALIAIALQACABALADIgCALIALAHQAJADAHgHIARAIQADADgFAGIgVAMQgBgIgGgEQgCgCgJgEIgNAGIABAHIAGALQACAFgCACIgMAVIgEADg");
	this.shape_15.setTransform(42.7,56.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#ED2256").s().p("AAAAOQgEAAgDgEQgEgFgBgDIAAgIIAAgHIAQAAIAJAJIAAARIgKABIgDAAg");
	this.shape_16.setTransform(234.7,31.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#ED2256").s().p("AgIANQgDgBgCgDQAAAAAAgBQAAgBAAAAQAAgBAAgBQAAAAAAgBIADgGQABgFACgDIADgHIAIACQAEABADAGQAEAFgBADQgBALgIAHQgIgEgFgBg");
	this.shape_17.setTransform(141.4,78.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#ED2256").s().p("ADiC4IgXAAQgKAAgCgCIgHgBIgYAAQgNAAgEgCIgHgBIgfAAQgHAAgDgBIgCgBIgKAAQgGgBgDgCQgGAAgIgCIgMgEIg7gTQgHgEgMgEIgUgHQgXgKgRgJQgUgLgMgKQgOgKgDgCIgFgEIgEgFIgGgEIgEgDIgagaQgCgFgLgKQgFgGAAgCIgCgCQgIgIgPgVIgUgdIgCgEIgGgMQgFgFgFgNIgJgPIgGgMQAAgEgFgIQgGgLgBgGQgGgHAAgFQAFgEALAAQAMAAAFgDQACgBAIABQALAAACgCIAHgBIAQgCIANAAIAKgCIAJgBIAIgBQAGAAACgCIAHAAQAOAAAFgCIAMgBQALAAAEgCQACgBAGAAQANAAAEgCIAKAAIAHgBIAHgBIAMgBIAGAAIAGgCQABgBAGAAIAJAAQAGAAAEgCQADgCAIABQAIAAACgBIAPgBQAIgBAGADQANAFAJAMIAEAIIAGgFIAnARQAKAFAFgBIAIACIAQAFQAEAAAFACIAJADIgDAaQgCABgFAAIgIABIgHAMQACAGADACQADAGgDAGQgDAEgBAGQAAAAAAAAQAAABAAAAQAAAAABABQAAAAABABQAAAAAAAAQABAAAAAAQAAAAABAAQAAAAABgBIAGgFIADgFQADgCADgBIADgCQAFgFAHgGIAPgKIAGgCIAGgLQACgEADgBIAJgEQAFgDAEgBQADAAAEgEQgHgCgCgJIgDgIIATgUQAJgCAHAFIANgNIAMACQAFAAACAFQAGARgGASQgEAFAEAFQAFAKgFANIgDAEQgCACgEgBQgFgBgCADQADABAFAFQAEAEAEABQAAAAAAAAQABABAAAAQABABAAAAQAAABAAABIABAKQAAAGgEAEIADAGIAAAIIAAAWQgBABgFAAQgEABgBACIgEAAQgDgDgBAEQgDAEADADIAHAGIgGAIQABAHAIAEIAMAFQABAAAAABQAAAAAAAAQAAABAAAAQAAABgBAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAIADAGQADAHAAAIIAAAaQAAAJACACIABAGIAAARQAAAKACAEIABAGIAAAWQAAAGgGACIgVALIgNAFQgGADgGAAQgEADgGAAIgLAAgACcBJQACAHgFAJQAEADADgEIADgIIAHAAQAFAAACgCQABAAAAgBQAAAAAAAAQABAAAAAAQAAABAAAAQACACAFAAQAFAAACACQADACADgCIAFgEQAEgEgEgGQgDgFAFgDIAJgHQAGgFAEgCIgFgBIgIACIgIABIgGAHQgDAHgGgBIgFAAIgHgKIgEAMIgUABQgDgEgEABQgFABgCAGQADAEAGAAIACAAQAEAAACABgABeBLQgFACgCACIAFABIAGAFIAGgGIgDgJQgCADgFACgABsgTIAHANIgEAJIgTAFIgEAHIAGAEIAJANIgBAHQAAAEgEAEIgBACIAFAHIADgDIAMgVQADgCgDgFIgGgLIgBgHIANgGQALAEACACQAGAEABAIIAWgMQAEgGgCgDIgSgIQgHAHgJgDIgMgHIABgLQgLgDgBgBIgIgLIAKgLQgCgFgEAAQgEAAgCAEIgGAJIgFALQACACABAFIAAAGIADgGgABIA1QAAAAABABQAAAAAAAAQABABAAAAQAAAAABAAQAAAAABAAQAAAAAAgBQABAAAAAAQAAgBAAgBIgDgDgACrAgIAGAIIADgFQgDgEgDAAIgDABgACDAfIAFAEQACgEgCgDgADrAbIgBACIACACIADgCIgBgDIgBAAIgCABgADCAUQgEADgCAEIAFABIAFgEQAAgBAAgBQAAgBgBAAQAAgBgBAAQAAAAgBAAIgBAAgACIAcQABAAABgBQAAAAABAAQAAAAAAAAQABAAAAgBIgBgDgAArAKQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABQADADAEgCIgEgDIgBgBIgCABgABTgBIAJgRIAAAAQgBAAAAAAQgBAAAAAAQgBAAgBAAQAAAAgBABQgCACgFACIgMADQgCAGACADIAGgCQAEAAAFACgADBhBQgGAFAEAFQACAFADABIAJAEIABALIAAAHIADAOIAAADIAEACIgCgGIABgEIABgDQABgFgBgCIgDgLIgDgMQgIgCABgKQABgFgDgCIgFAFgAA9gdIACAAIgBgFIgBAAgAA+g5IgGAGIAAACIAAABQABAAAAABQABAAAAAAQABAAAAAAQAAAAAAAAIAHgGIABgCIgBgCIgDAAIgBAAgABIhTQADACAAAFQgBAFACABIACgBQAFgHgIgGgADlhaQgDACgBADQgBADABACIAIAJIAOgMIgQgHIgBAAIgBAAg");
	this.shape_18.setTransform(29.9,56.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#ED2256").s().p("AB4DdQgFgDgOAAImDAAQgNAAgHgJIgEgEIAAhtQAAgJACgFIABgJIAAiqIgBgLIACgKQADgGgDgGQgDgHADgGQADgHgCgFIgCgOQAAgFgCgCQgCgDABgKIADAAIAKgBQAGgBADgBIAKAAIAHgBQAEAAACgCIAFgBQAMAAAGgCIAPAAQAHAAAEgCQADgCAHABQAMAAADgCIAIgBIAJAAIAJgCIAKAAIAOgCIAJgBIAIAAQAEAAAEgDQACgBAIABQAKAAAEgCQACgBAHAAQAMAAAEgBIAJgBIAIAAQAFAAADgCIAFAAIAABEQAAAIACADIABAHIAAAUQADAFAPAKQAGAEAHAAIAdgBQAHAAADgBQACgBAIAAICXAAQALAAAEgCIAHAAIBQAAQADAAADADIABAEQAIAHgGAKIgDAHQgEAGADADQADAEgCACQgDAFgCANIgGALIgIAMIAAAHIgCAPQgCAJgEAHQgCAFgDAPIgCAJQgEAHABAGQAAAGgDALIgEAKQgCAIgIATIgBACQgIAIAGAGIgBAMIgEANIgDANIgEAOQgCAGgFAEQgKAIgOAHQgLAGgLAAg");
	this.shape_19.setTransform(98.6,53.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#ED2256").s().p("Ag+FCQgGAAgBgBQgDgCgKAAIibAAQgQAAgHgKIgDgDIAAivQAAgJADgEQABgBAAgIIAAhNQAAgGAFgCIAFgEQAMgHAKAAIAOAAIAOACIAIABQAFAAADACIAGAAIAMACQABABAGAAIAZAAQAPABAUgJQASgGAEgKIADgEIAEgIIADgMQABgIgBgFIAAgCQABgIgGgXQgDgJgGgGQgKgPgHgFQgFgFgCgGQgCgHgGgFIgpgpIgngoIgEgDQgEADgRAAQgFABgBgFQgCgFgEgFIgJgJIAAgBQgBgGACgGIADgMIACgGQgBgDACgFIACgIIAHgBQAWgDAIAAQAFgCAQAAIAFgBQAEgCAKAAQALAAAEgCIAGgBQAOAAAFgCQAEgCAKABQAJAAADgBQACgBAGAAIAJAAIAJgCIAMgBQAIAAADgCIAIgBIAJAAQAGAAADgCQACgBAHAAQAKAAADgCIADAAIADAAQAMAAAEgCIAMgBIALgCIAJgBIARgCIANAAIAKgCQAJgCAHACQAFAAAHAHIA1A1IAIAKQAGAIABACIAEAFQAEADAAADQADACAEAHQACAHAEACQACAIAHANIAIATQAEAHAAAGQABAGAEAKIAEAUIACAGIABACQgBAFACAIQACAIAAAEQgBAHACAGQABABAAAHIAAAeQAAAHACADQAEAFgEAHIgFAQQgCAHAAAJQAAAHgCACIgBABQABAHgEAMIgGAZIgNAmIgFANQgFAPgDAFQgDAEgCAIQgHAOgNATQgKARgRAQIgXAXIgIAGIgEAEQgIAHgQAKQgbASgVAGIgPAEQgLACgNAJQgJAFgCADIgIAEQgGACgFAAg");
	this.shape_20.setTransform(262.7,43.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#ED2256").s().p("AlUE6IgJgIQgFgFADgGQAGgLAFgFQgHgJAAgIQAAgEgDgCQgDgDgEACQgHADgVAAQgJgBgMAFQgJAEgIgEQgGgDgFACQgFADgKgEQgFgCgGAAIgdAAIgEgGIgDgDQgGgFADgGQACgDABgIIAEgLIADgOQABgJACgEIADgJIACgJIADgPIADgHIAFgSIAEgKIACgKQABgHADgEIAFgNQAHgPABgIIACgHIAAgEQADgGAAgIQACgDAAgHQABgHACgDQgBgCACgEIACgFIALgkIAKggIAJgcIABgEQADgDgCgIQgLgBgDgKIgCgCIgDgGQAAgBAEgEIAHgIQAGgHAIAEIAGABQAFgFACgLIADgMIACgEQABgDgCgCQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAgBAAgBIgBgFQgDgEAEgEQALgLAGgQIgCgEQgDgLAKgDIAIgDQAFgBADAAQAKACAHgEIAIAAQAMAAAEgCIAMgBQAJAAADgCIAHgBQAMAAADgCIAHAAIAJAAIAJgCIANgBIAPgCIAIgBIAIAAQAFAAADgCQADgCAIABQAJAAAFgBQADgCAJABQAJAAADgCIAHgBIAJAAQAGAAAEgCIAIgBIAIAAIAIgCIAMAAQAIAAAEgCIAIgBQABAGgCAFIgNAoIgCAJQgJAZgCAJQgCACAAAEIgCAFIgBAGIAFABIBMAAIAFgBQAMgEAPAEIAMAEQAIAFAKgFIADgCIAAgPQAAgNACgFQACgHgEgJQgIgRgBgJQgEgFgDgJQgDgLgDgEQgCgDgBgGIgCgKQACgBAHAAQAJAAAFgCQACgBAKAAQAJAAADgCIAIgBQAOAAAEgCIAIAAIAQgCIAOgBIAHAAQADAAADgCIAGgBIAKAAIAKgCIALAAQAIAAAEgCQADgCAHABQAMAAADgCIAIgBIARgCIANAAIAKgCIAKgBIAMgCQAEgCAIABQAFAAACAGIAKAjIACAJIgCAIQAIAIABAJIAAABQAGAIAGAUIABAFQAAAGAGAPQACADAAADIACANQACAHgBAGQAGAFAAABIAHAVIAGAVQAEAGADAOIAIAZIAJAeIAEAKIAFATIAGAOIACAJIADAIQADAFACAMIAIAcIABADQADAGAAADIgEAJIAGAGQAHAHAHASIAIAXIADAMIAFALQABADABAIIAKAfIAHAXIgFAGIgFAHIgHABQgFAAgDACIh+AAIgEgFIgCABQgFAFgIgBIg9AAQgGAAgEgCIgJgBIgxAAQgDgHgBgDIgFgRIgFgRIgNgoIgEgLIgDgJQgEgHgIgDIgcgIQgHgBgDABQgEACgKAAIgPAAQgGAAgDACIgIABIgiAAIgHAAQgFADgNAAIiGAAQgLAAgEABQgBABgGAAIgTAAQgMAWgGATIgBADQgDAEgCAJIgFANIgHARQgFAKgBAGIgEAIQgCAEgEAAIgMACQgIACgHgCIgMgCIgGgBQgKgEgHAFQgDACgFAAQgFABgCABQgBgBgFAAQgEAAgCgCIgHgDQgDABgCAEIgDAGIgHAIQgCACgGABQAAAAAAABQAAAAAAABQABAAAAABQABAAABAAIAJAFQAHAEAAAFQAAAAAAABQAAABAAAAQAAABAAAAQABAAAAAAQADAEgEAGQgHAKgMAAIgHgBg");
	this.shape_21.setTransform(178.5,49.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#ED2256").s().p("Al7F6IgCgCIgLgLIAAgNIAAmkQAAgMACgEIABiuQAAgKABgCIAFgBQAKgBgEgKIgEgIIACgCQACAAAHgBIAJgCQALABAHgDIALgBQAIAAADgCIAHAAIAMAAQAHAAAFgCIAJgBQAKAAADgCQADgBAGAAQANAAAEgCIAJAAIAIAAQAEgBADgBIAGgBQANgBACgCIALAAQALAAADgCQACgBAHAAQAMAAAEgCIACAAQAGgBACADQABACgBAGIAAACIAEABIDsAAQAMAAAEADIAHAAQABgEAAgSIAAgUIAGgEIALgCQAHgCAEAAQALABAEgCIAIgBIAJAAQAFAAAEgCIAKgBQAIAAAGgCQADgBAJAAQAJAAACgCIAIAAIAJAAQAGAAADgCIALgBIAIAAIAIgCIALgBIAOgCQACgBAIAAQAKAAAFgBQACgCAFABQANAAAEgCIAIgBIAIAAIABBVQAAAIABAEQABACAAAIIAABfQABANADADIAAAGIAABgQAAAGgCADQgBAAAAABQAAAAAAABQAAAAAAABQgBABAAAAIAAGSQABAGgFADIgIAFQgEADgFgCIgIAAIhGAAQgKAAgEABIgGABIh/AAIgBgBIgLgLIAAgPIAAgbQAAgJACgEIAAgKIAAlGQgCgCgHAAIhBAAQgMAAgEgCIgGgBIilAAIgHABIAAAFIAAAaQAAAIgCAEIgBAFIAAAXQACAFABAHIAAAOIAABKQgBAIACACIABAIIAABoIgBAFQgBAEAAAOIAAAgIgBAJQAAAFACAEIABACIgBAdIgHADIgGAGIgIABQgFAAgCACIgIABg");
	this.shape_22.setTransform(337.5,37.9);

	this.addChild(this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,376.9,81.5);


(lib.books = function() {
	this.initialize();

	// Calque 1
	this.instance = new lib.book1();
	this.instance.setTransform(66.3,8.8,0.664,0.664);

	this.instance_1 = new lib.book2();
	this.instance_1.setTransform(0,0,0.664,0.664);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,150,149.7);


(lib.slogan = function() {
	this.initialize();

	// Calque 1
	this.instance = new lib.jay_crownover();
	this.instance.setTransform(55.2,117.2,0.829,0.829,0,0,0,89.2,8.8);
	this.instance.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,10);

	this.instance_1 = new lib.nouvelle_serie();
	this.instance_1.setTransform(117.8,9.2,1,1,0,0,0,115.8,9.2);
	this.instance_1.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,8);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-24.7,-7.4,163,142.4);


(lib.btn = function() {
	this.initialize();

	// Calque 2
	this.instance = new lib.discover_bold();
	this.instance.setTransform(55.7,9.4,0.56,0.562,0,0,0,62.6,10.3);

	// Calque 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#51A5B6").s().rr(-68.2,-10.55,136.4,21.1,2);
	this.shape.setTransform(55.4,10.5,0.812,1);

	this.addChild(this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,110.8,21.1);


// stage content:
(lib.clash_120x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{loop_btn:174});

	// timeline functions:
	this.frame_196 = function() {
		this.gotoAndPlay('loop_btn');
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(196).call(this.frame_196).wait(1));

	// btn
	this.instance = new lib.btn();
	this.instance.setTransform(59.9,542.4,1,1,0,0,0,55.4,10.5);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(150).to({_off:false},0).to({y:519.6,alpha:1},14,cjs.Ease.get(1)).wait(10).to({scaleX:0.9,scaleY:0.9},11).to({scaleX:1,scaleY:1},11).wait(1));

	// books
	this.instance_1 = new lib.books();
	this.instance_1.setTransform(60,218.9,0.303,0.303,0,0,0,75,74.7);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(60).to({_off:false},0).wait(1).to({regY:74.8,scaleX:0.3,scaleY:0.3,alpha:0.002},0).wait(1).to({scaleX:0.31,scaleY:0.31,y:218.8,alpha:0.008},0).wait(1).to({scaleX:0.31,scaleY:0.31,y:218.7,alpha:0.019},0).wait(1).to({scaleX:0.32,scaleY:0.32,y:218.6,alpha:0.034},0).wait(1).to({scaleX:0.32,scaleY:0.32,y:218.4,alpha:0.053},0).wait(1).to({scaleX:0.33,scaleY:0.33,y:218.2,alpha:0.077},0).wait(1).to({scaleX:0.34,scaleY:0.34,y:218,alpha:0.105},0).wait(1).to({scaleX:0.35,scaleY:0.35,y:217.6,alpha:0.137},0).wait(1).to({scaleX:0.37,scaleY:0.37,y:217.3,alpha:0.174},0).wait(1).to({scaleX:0.38,scaleY:0.38,y:217,alpha:0.215},0).wait(1).to({scaleX:0.4,scaleY:0.4,y:216.6,alpha:0.26},0).wait(1).to({scaleX:0.42,scaleY:0.42,y:216.1,alpha:0.308},0).wait(1).to({scaleX:0.43,scaleY:0.43,y:215.7,alpha:0.359},0).wait(1).to({scaleX:0.45,scaleY:0.45,y:215.2,alpha:0.413},0).wait(1).to({scaleX:0.47,scaleY:0.47,y:214.7,alpha:0.469},0).wait(1).to({scaleX:0.5,scaleY:0.5,y:214.2,alpha:0.528},0).wait(1).to({scaleX:0.52,scaleY:0.52,y:213.7,alpha:0.588},0).wait(1).to({scaleX:0.54,scaleY:0.54,y:213.1,alpha:0.649},0).wait(1).to({scaleX:0.56,scaleY:0.56,y:212.5,alpha:0.712},0).wait(1).to({scaleX:0.59,scaleY:0.59,y:212,alpha:0.775},0).wait(1).to({scaleX:0.61,scaleY:0.61,y:211.4,alpha:0.838},0).wait(1).to({scaleX:0.63,scaleY:0.63,y:210.9,alpha:0.895},0).wait(1).to({scaleX:0.64,scaleY:0.64,y:210.5,alpha:0.937},0).wait(1).to({scaleX:0.66,scaleY:0.66,y:210.3,alpha:0.967},0).wait(1).to({scaleX:0.66,scaleY:0.66,y:210.1,alpha:0.986},0).wait(1).to({scaleX:0.67,scaleY:0.67,y:210,alpha:0.997},0).wait(1).to({regX:74.9,scaleX:0.67,scaleY:0.67,y:209.9,alpha:1},0).to({scaleX:0.7,scaleY:0.7,x:60.5,y:209.3},52).wait(1).to({regX:75,scaleX:0.7,scaleY:0.7,y:212.3},0).wait(1).to({scaleX:0.7,scaleY:0.7,y:215.9},0).wait(1).to({scaleX:0.7,scaleY:0.7,x:60.4,y:220.1},0).wait(1).to({scaleX:0.7,scaleY:0.7,y:225},0).wait(1).to({scaleX:0.69,scaleY:0.69,x:60.3,y:230.4},0).wait(1).to({scaleX:0.69,scaleY:0.69,y:236.4},0).wait(1).to({scaleX:0.69,scaleY:0.69,x:60.2,y:242.9},0).wait(1).to({scaleX:0.69,scaleY:0.69,y:249.8},0).wait(1).to({scaleX:0.69,scaleY:0.69,y:256.9},0).wait(1).to({scaleX:0.68,scaleY:0.68,x:60.1,y:264.3},0).wait(1).to({scaleX:0.68,scaleY:0.68,x:60,y:271.8},0).wait(1).to({scaleX:0.68,scaleY:0.68,y:279.3},0).wait(1).to({scaleX:0.68,scaleY:0.68,x:59.9,y:286.8},0).wait(1).to({scaleX:0.67,scaleY:0.67,y:291.9},0).wait(1).to({scaleY:0.67,y:294.1},0).wait(1).to({regX:74.9,scaleX:0.67,y:294.9},0).wait(42));

	// books text
	this.instance_2 = new lib.slogan();
	this.instance_2.setTransform(59.8,331.7,0.624,0.624,0,0,0,55.2,60.5);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(79).to({_off:false},0).to({regX:55.1,scaleX:0.76,scaleY:0.76,x:59,y:350.3,alpha:1},38,cjs.Ease.get(0.5)).to({regX:55.3,scaleX:0.78,scaleY:0.78,x:59.4,y:354.6},22,cjs.Ease.get(-0.5)).wait(1).to({regX:55.2,regY:60.6,scaleX:0.78,scaleY:0.78,x:59.3,y:357.3},0).wait(1).to({scaleX:0.77,scaleY:0.77,y:360.4},0).wait(1).to({scaleX:0.77,scaleY:0.77,x:59.2,y:364},0).wait(1).to({scaleX:0.77,scaleY:0.77,y:368.1},0).wait(1).to({scaleX:0.76,scaleY:0.76,y:372.6},0).wait(1).to({scaleX:0.76,scaleY:0.76,x:59.1,y:377.7},0).wait(1).to({scaleX:0.76,scaleY:0.75,x:59,y:383},0).wait(1).to({scaleX:0.75,scaleY:0.75,y:388.7},0).wait(1).to({scaleX:0.75,scaleY:0.75,y:394.7},0).wait(1).to({scaleX:0.74,scaleY:0.74,x:58.9,y:400.8},0).wait(1).to({scaleX:0.74,scaleY:0.74,y:407.2},0).wait(1).to({scaleX:0.73,scaleY:0.73,x:58.8,y:413.6},0).wait(1).to({scaleX:0.73,scaleY:0.73,x:58.7,y:420.2},0).wait(1).to({scaleX:0.72,scaleY:0.72,y:426.3},0).wait(1).to({scaleX:0.72,scaleY:0.72,x:58.6,y:429},0).wait(1).to({regX:55.3,scaleX:0.72,x:58.7,y:429.5},0).wait(42));

	// clash_top
	this.instance_3 = new lib.clash_top();
	this.instance_3.setTransform(15.6,209.2,0.505,0.505,0,0,0,190.1,39.6);
	this.instance_3.alpha = 0;
	this.instance_3.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,8);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({regY:39.5,scaleX:0.26,scaleY:0.26,x:58.8,y:209.6,alpha:1},17,cjs.Ease.get(-0.5)).to({regX:189.9,regY:39.7,scaleX:0.27,scaleY:0.27,x:56.4,y:206.9},42).to({regX:190.1,regY:39.6,scaleX:0.51,scaleY:0.51,x:35.6,y:184.2,alpha:0},14,cjs.Ease.get(1)).to({_off:true},1).wait(65).to({_off:false,regY:39.7,scaleX:0.28,scaleY:0.28,x:59,y:81.9},0).to({alpha:1},25,cjs.Ease.get(-0.5)).wait(33));

	// clash_bottom
	this.instance_4 = new lib.clash_bottom();
	this.instance_4.setTransform(105.4,251,0.505,0.505,0,0,0,188.5,40.5);
	this.instance_4.alpha = 0;
	this.instance_4.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,8);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({regX:188.7,regY:40.4,scaleX:0.26,scaleY:0.26,x:61.8,y:220.8,alpha:1},17,cjs.Ease.get(-0.5)).to({regX:188.4,regY:40.3,scaleX:0.27,scaleY:0.27,x:64.8,y:217.9},42).to({regX:188.5,regY:40.5,scaleX:0.51,scaleY:0.51,x:85.4,y:246,alpha:0},14,cjs.Ease.get(1)).to({_off:true},1).wait(65).to({_off:false,regY:40.4,scaleX:0.28,scaleY:0.28,x:62.2,y:94.1},0).to({alpha:1},25,cjs.Ease.get(-0.5)).wait(33));

	// clash text
	this.instance_5 = new lib.clash_text();
	this.instance_5.setTransform(60.8,305.7,0.911,0.911,0,0,0,45.1,39.8);
	this.instance_5.alpha = 0;
	this.instance_5.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,8);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(15).to({_off:false},0).to({scaleX:1,scaleY:1,x:61.1,y:308.1,alpha:1},44,cjs.Ease.get(1)).to({_off:true},1).wait(79).to({_off:false,scaleX:0.92,scaleY:0.91,x:61,y:183,alpha:0},0).to({regX:45.3,scaleX:0.91,scaleY:0.9,x:60.7,y:182.5,alpha:1},25).wait(33));

	// logo
	this.instance_6 = new lib.logo();
	this.instance_6.setTransform(48.1,558.1,0.6,0.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(197));

	// bg
	this.instance_7 = new lib.background();

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(197));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-28.3,300,304.5,600);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;