(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



(lib.background = function() {
	this.spriteSheet = ss["clash_300x600_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.book1 = function() {
	this.spriteSheet = ss["clash_300x600_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.book2 = function() {
	this.spriteSheet = ss["clash_300x600_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.logo = function() {
	this.spriteSheet = ss["clash_300x600_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.nouvelle_serie = function() {
	this.initialize();

	// Calque 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAPEZIAAiIIBGAAIAAAXIgsAAIAAAeIArAAIAAAXIgrAAIAAAlIAsAAIAAAXgAhkEZIAAiIIAmAAQAOAAAMAFQAMAFAKAJQAIAKAFAMQADANAAAOQAAAOgDANQgFAMgJAJQgJAJgMAGQgMAFgOAAgAhKECIAFAAQAYAAAKgMQALgMAAgVQAAgtgtAAIgFAAgARthIQgNgGgMgMQgLgLgFgPQgGgPAAgRQAAgPAGgQQAFgQALgLQALgNANgGQAPgHARAAQASAAASAKIAAAlQgHgJgJgEQgJgEgKAAQgLAAgIAFQgJADgHAJQgGAHgDAKQgDAKAAAKQAAALADAJQADAJAHAIQAGAIAJAEQAIAFALAAQAJAAAJgFQAJgEAIgIIAAAkIgSAIQgJACgJAAQgRAAgOgHgAPIhIQgPgGgKgLQgKgMgGgPQgEgPAAgSQAAgRAEgQQAHgOAJgMQAKgLAPgHQAPgGASAAQARAAANAGQAPAHALALQALAMAFAOQAGAQgBARQABASgGAPQgFAPgLAMQgKALgPAGQgOAHgRAAQgSAAgPgHgAPVjFQgJAEgGAIQgGAHgCAJQgFAJAAAKQAAAJAEAKQACAKAFAIQAGAHAIAGQAKAEANAAQALAAAJgEQAKgGAFgHQAGgIACgKQACgKAAgJQAAgKgDgJQgDgJgGgHQgGgIgIgEQgJgEgKAAQgLAAgJAEgAK9hIQgOgGgKgMQgLgLgGgPQgFgPgBgRQABgPAFgQQAGgQALgLQAKgNAOgGQAOgHARAAQASAAASAKIAAAlQgHgJgJgEQgJgEgKAAQgLAAgIAFQgJADgHAJQgFAHgDAKQgEAKAAAKQAAALAEAJQADAJAGAIQAGAIAJAEQAIAFALAAQAJAAAKgFQAJgEAHgIIAAAkIgSAIQgJACgJAAQgRAAgOgHgACDhJQgMgJgJgOIAVgTQACAJAIAHQAIAGAJAAQAJAAAHgGQAEgHAAgJQABgFgCgFIgGgHIgHgEIgKgEIgDgBQgIgDgGgEIgLgJQgFgFgCgGQgDgIAAgIQAAgKAEgJQADgJAHgGQAFgHAJgDQAIgEAKAAQAMAAAMAFQAMAFAHAIIgOAVQgFgGgGgDQgFgEgHAAQgIAAgGAFQgGAGAAAHQAAAIAGADQAFAFANAFIAOAHQAHADAFAGQAGAFADAIQAEAIAAALQAAAYgOAPQgOAPgYAAQgQAAgMgIgAmUhBIg8iiIAhAAIAlBqIABAAIAjhqIAhAAIg9CigAouhGQgLgFgHgJQgHgJgDgNQgEgMAAgPIAAheIAfAAIAABYIABAQIADAPQAEAHAFAFQAGAEAJAAQAJAAAGgEQAGgFADgHQADgGAAgJIABgQIAAhYIAfAAIAABeQAAAPgDAMQgEANgHAJQgGAJgMAFQgLAFgQAAQgPAAgMgFgArKhIQgQgGgJgLQgLgMgFgPQgGgPABgSQgBgRAGgQQAGgOAKgMQAKgLAPgHQAOgGARAAQASAAAOAGQAPAHAKALQALAMAFAOQAGAQAAARQAAASgGAPQgFAPgKAMQgLALgOAGQgPAHgSAAQgRAAgOgHgAq+jFQgIAEgHAIQgFAHgDAJQgEAJAAAKQAAAJADAKQACAKAFAIQAHAHAIAGQAJAEAMAAQANAAAJgEQAJgGAFgHQAGgIACgKQADgKAAgJQAAgKgEgJQgCgJgHgHQgFgIgJgEQgJgEgLAAQgKAAgJAEgAsdhCIhUhvIgBAAIAABsIgdAAIAAijIAVAAIBUBvIAAhqIAfAAIAAChgANshFIAAhHIg6AAIAABHIgeAAIAAieIAeAAIAAA9IA6AAIAAg9IAeAAIAACegAHzhFIAAieIBSAAIAAAaIg0AAIAAAjIAyAAIAAAbIgyAAIAAArIA0AAIAAAbgAG+hFIAAieIAeAAIAACegAGOhFIgmhAIgBAAIAABAIgeAAIAAieIAqAAQAYAAAOALQAOAMAAAYQAAARgJAMQgIAMgPADIAtBDgAFniaIAFAAQANAAAIgGQAIgGAAgNQAAgOgIgEQgHgFgOAAIgFAAgADjhFIAAieIBRAAIAAAaIgzAAIAAAjIAxAAIAAAbIgxAAIAAArIAzAAIAAAbgAgthFIAAieIBQAAIAAAaIgxAAIAAAjIAvAAIAAAbIgvAAIAAArIAxAAIAAAbgAiBhFIAAieIAeAAIAACDIAsAAIAAAbgAjWhFIAAieIAfAAIAACDIAsAAIAAAbgAk8hFIAAieIBSAAIAAAaIg0AAIAAAjIAyAAIAAAbIgyAAIAAArIA0AAIAAAbgAv3hFIgMghIg3AAIgNAhIhoAAIAAieIAfAAIAACDIArAAIAAATIA8ibIAXAAIA8CjgAwMiAIgTg5IAAAAIgSA5IAlAAgAD5j0IAagkIAUAOIgfAfg");
	this.shape.setTransform(120,28.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,240,56.3);


(lib.jay_crownover = function() {
	this.initialize();

	// Calque 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#ED2256").s().p("AJEBXIg/ipIAiAAIAoBuIABAAIAlhuIAiAAIhACpgAGQBQQgPgHgLgMQgLgMgGgQQgFgPAAgSQAAgRAGgQQAFgQALgMQALgMAPgGQAQgHASAAQASAAAPAHQAPAGALAMQALAMAGAQQAGAQAAARQAAASgGAPQgGAQgKAMQgLAMgPAHQgQAHgSAAQgTAAgPgHgAGegxQgKAEgGAIQgGAIgEAJQgDAKAAAKQAAAIADAKQACAKAGAIQAGAJAKAFQAJAFANAAQANAAAJgFQAJgFAGgJQAGgIADgKQACgKAAgIQAAgKgDgKQgDgJgHgIQgGgIgJgEQgJgFgLAAQgLAAgJAFgAiYBQQgPgHgLgMQgLgMgGgQQgFgPAAgSQAAgRAGgQQAFgQALgMQALgMAPgGQAQgHASAAQASAAAPAHQAPAGALAMQALAMAGAQQAGAQAAARQAAASgGAPQgGAQgKAMQgLAMgPAHQgQAHgSAAQgTAAgPgHgAiKgxQgKAEgGAIQgGAIgEAJQgDAKAAAKQAAAIADAKQACAKAGAIQAGAJAKAFQAJAFANAAQANAAAJgFQAJgFAGgJQAGgIADgKQACgKAAgIQAAgKgDgKQgDgJgHgIQgGgIgJgEQgJgFgLAAQgLAAgJAFgAmWBQQgPgHgLgMQgLgMgGgQQgGgPAAgRQAAgQAGgQQAGgQALgMQALgMAPgIQAPgHASAAQATAAASAKIAAAnQgHgJgKgFQgKgEgKAAQgLAAgJAFQgKAEgGAJQgGAHgEALQgDAKAAAJQAAALAEAKQADAKAGAIQAHAIAJAEQAJAFALAAQAKAAAKgFQAJgFAIgHIAAAmQgKAFgKACQgJADgJAAQgRAAgPgHgAtrBSQgJgEgHgHIAVgXQABAEAEADQAEADAEABQAEAAADgEQADgDABgEIACgMIAAgPIAAhnIAhAAIAABsQAAAPgCAJQgCAJgGAJQgGAKgKAEQgKAFgLAAQgJAAgIgFgAE5BWIhYhyIAABuIggAAIAAioIAXAAIBXByIABAAIAAhuIAgAAIAACogABoBWIghhqIgBAAIgfBqIgYAAIgyioIAhAAIAgBwIAAAAIAhhxIAUAAIAiBxIAAAAIAhhwIAiAAIg4CogANVBSIgphDIAABDIggAAIAAikIArAAQAaABAPAMQAPAMAAAaQAAARgJANQgJALgQADIAvBFgAMsgFIAEAAQAPAAAIgFQAHgHAAgNQAAgPgHgFQgIgFgPAAIgEAAgAKgBSIAAikIBWAAIAAAdIg1AAIAAAkIAzAAIAAAaIgzAAIAAAtIA1AAIAAAcgAjyBSIgphDIAABDIggAAIAAikIArAAQAaABAPAMQAPAMAAAaQAAARgJANQgJALgQADIAvBFgAkbgFIAEAAQAPAAAIgFQAHgHAAgNQAAgPgHgFQgIgFgPAAIgEAAgApcBSIAAhMIgzhYIAlAAIAdA6IAgg6IAmAAIg1BYIAABMgAqsBSIgNgiIg5AAIgOAiIgiAAIBAioIAaAAIA+CogArCAVIgVg6IgSA6IAnAAg");
	this.shape.setTransform(89.2,8.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,178.5,17.5);


(lib.discover_bold = function() {
	this.initialize();

	// Calque 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJBYQgRgQAAgbIAAhjIAgAAIAABeQAAASAHAIQAHAJARAAQAQAAAIgJQAHgIAAgSIAAheIAhAAIAABjQAAASgHANQgIANgPAHQgPAHgUAAQgeAAgPgPgAi7BSQgTgVAAgnQAAglATgVQATgUAlAAQAkgBATAWQATAUAAAmQAAAmgTAVQgUAVgkAAQgkAAgTgVgAihgQQgLAOAAAZQAAAZAKAOQAKANAUAAQAoAAAAg0QAAg0gnAAQgUAAgKANgAlIBSQgSgVAAgmQAAgXAIgSQAJgTARgJQARgKAWAAQAXgBAXAMIgLAbQgIgFgJgCQgJgDgJAAQgTAAgKANQgKAOAAAYQAAA0AnAAQARABAXgJIAAAcQgTAIgYAAQgiAAgSgVgAJOBlIgmg8IgSAAIAAA8IghAAIAAibIAuAAQAgAAAPALQAQANAAAXQAAAMgIALQgIAKgOAHIAuBEgAIWAOIALAAQAQgBAHgEQAIgGAAgJQAAgMgIgEQgHgFgRAAIgKAAgAGsBlIAAibIAhAAIAACbgAF0BlIgmg8IgSAAIAAA8IghAAIAAibIAuAAQAgAAAPALQAQANAAAXQAAAMgIALQgIAKgOAHIAuBEgAE8AOIALAAQAQgBAHgEQAIgGAAgJQAAgMgIgEQgHgFgRAAIgKAAgACuBlIg2ibIAiAAIAdBbIAGATIADAQQABgKAHgZIAehbIAhAAIg1CbgAnOBlIAAibIBaAAIAAAbIg5AAIAAAhIA1AAIAAAbIg1AAIAAAoIA5AAIAAAcgApxBlIAAibIAxAAQAmAAAWAUQAVAVAAAiQAAAngWAUQgWAVgqAAgApQBJIAOAAQAwABAAg0QAAgxgsAAIgSAAgAm1hDIAAgDQATgVAHgLIAkAAIAAADIgTAQIgVAQg");
	this.shape.setTransform(62.7,10.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,125.4,20.7);


(lib.clash_top = function() {
	this.initialize();

	// Calque 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#ED2256").s().p("AgLALIgFgJQAIgCADgBIAFgJIARABIgCAEQgEAFgCAHIgGAAIgIADIgEABg");
	this.shape.setTransform(251.2,22.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#ED2256").s().p("AgOASQgCgCgEgFIADgCQAHgFABgDIACgKIAAgLIABgCQAMACAPgCIgWAtIgNgFg");
	this.shape_1.setTransform(255.9,23.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#ED2256").s().p("AAAAOIgJgDQgBgFgCgDQgEgEAGgHIAEgFIAFAAQAIgEAHAKQAAAHgHALQgBAEgEAAIgCgBg");
	this.shape_2.setTransform(146,52.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#ED2256").s().p("AAAAbQAAgCAAgFIAAgHIgEgCQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQgBAAgBgBIgHgDIAAgEIAJgWQADgCAEACQADACACAAIAEAIQAFAGgDAHIABACQAEADAAAHIABAMIgKAGIgDABIgEgBg");
	this.shape_3.setTransform(142,58.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#ED2256").s().p("AiCCtIAAg8QACgFAAgNIABkLIACgDIAKgKIAPgBIDEAAQAOABAEACIAHAAIAJAKIAABuQABAKgDADIAAAJIAADBQgBAHgHAAIgIAAIgHABQgDAAgDABQgCABgGAAIgKAAQgHAAgDADIgIAAQgNAAgDACIgLABQgKAAgEABIgKABIgHAAQgFAAgBACIgHABQgNAAgEACIgJABQgJAAgEABIgGABQgPABgFACIgHAAIgQACIgLABQgMAAgDACIgDAAQgEgEgBgJg");
	this.shape_4.setTransform(367.1,21.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#ED2256").s().p("AhzDQIgGgPQgHgTACgSQACgDAAgIQABgHABgFIAAgGIACgFQADgDABgEIABgHIAAgIIgIgHQgFgFADgFQAFgKgEgMQgCgKAAgPIAAiNQgBgLgCgDIgBgFIAAhFQAIgFgCgHQAHgGAKAAIA8AAIAJAAQAGABAEACQAEACADgDQAEgCAHAAIARAAQAHABAEgCIAFgBIBfAAIAMAMIABAQIAAFuQgCAFgEAAIgRADQgKACgGgBIgDAAQgCACgNAAIgRACIgEABIgFgBIgOADIgLABIgOACQAAABgHAAQgLAAgGABIgKABQgJAAgDACIgKAAIgNADQgBABgHAAIgSABIgMABQgJAAgDADQgEgBgBgFg");
	this.shape_5.setTransform(314.3,24.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#ED2256").s().p("AiIFYIAAgLIAAgVQAAgEABgHQACgIAAgDIABgLIACgKQACgDABgHQABgHACgDIAIgBQAIAAADgBQACgCAGABQAJAAACgBQgBgLgJgEIgKgFQAAgRgLgHIgJABQgGgIABgIIABgEQADgDgBgEIgDgGQgHgSAEgKIABgFQAAgJAFgKQgEgEABgHQAAgOgCgFIAAgJIAAidQAAgJgCgFIgBgKIAAifIAAgJQAAgFgDgDIAAgEIAAg6IAMgNIAfAAIAEABQADACAMAAIAqAAQANAAADADIAKAAQAGAAADgBQACgCAGAAIAuAAQAIAAADgCIAHgBIAyAAQAHABAEAEQAEAEABAHIAAEJQAAAMgCAFIgBAHIAADRQAAAHACADIABAKIAABTQAAAJACACIgDAFQACASgDAIIgBAIIgBALQgUAFgLgBIgDAAQgFACgQAAIgEAAQgEADgGAAIgLAAQgHAAgDACQgBABgIAAIgRACIgNAAIgIACIgKABIgIAAQgFABgDACIgHAAQgNAAgFACIgMABQgIAAgDABQgCABgHAAIgIABQgFAAgEACIgKAAIgHABQgEAAgDABIgHABQgCgEAAgHg");
	this.shape_6.setTransform(84.8,36.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#ED2256").s().p("AjREHIgBgDQAAgDgDgCQgIgEgFgKQgKgVgGgTIgBgJQgBgKgBgDQgBgBAAgNQAAgIADgDQgFgJgBgJIgCgKIAAgLIgBgEQgCgCAAgEIAAgHIAAgXQAAgKACgDIABgIIAAgKQAAgGACgEIAAgHIABgHQACgCAAgHQAAgJACgCIABAAIACgUQAAgGADgFQADgDAAgIQgBgJAGgEQAHgFABgKQAEgLABgGQABgIAKgOQAJgOAEgCIADgCQAKgFAAgKIAHgMIAZgYQALgLANgCQAFgBABgEQACgGAJgFIAQgKIAQgIIAGgBQADAAAKgEIAEgCQADAAAGgBQAFgCADAAQAFABAEgDQAAAAABAAQAAAAABAAQABAAAAAAQABAAAAAAQAGAEAEgGQAEgEAIAAQAJABAFgEQACgBAFACIANAEQAKgOACgFIAMAFQAIAEADAFQAFgDADgEIAEgGQAFgFAGADIAMAFIgBAGIACABQAIgGALAIQAFAEAFAAIADAAIAFACQADABADgBIAKgEIALAKIALABIAYACIAFABQAJAEAGgFQAFgEAGACIALADQABAAAAABQABAAAAABQABAAAAABQAAAAAAABIAAAGIAAAbQAAAMgCAEIAAAJIAABTIgBAMIAGAHIAAA9QAAAIACADQABABAAAEIAAAdIgJAKIgOAAIgCgDQgBgBAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAIgDACIgBAAIgxgSQgHABgSgGIgOgEQAAgIgJgEIgKgHIgBgDQgDABgDALIgJABQgCAIgDACIgNAOIgHAGQgKAEACAKIgBAEQgPALgMgBQAAADACACIADADQADAEAAACQgBAFAGALIACACQAEAHgHADIgIAFIgDAGQADADAGABQAHACACABIABAMQASAVAFAFIAcAcQALALAFADIAHAGIAGAHIgBACQgHgBgMACQgNACgHgBIgDAAQgDADgQAAIgJACQgBABgFAAIgKABQgGgBgFACIgKAAIgNACIgKABIgHAAQgDABgDACIgDABIgFAAQgMAAgFABIgKABQgKAAgEACIgIAAIgKABQgGAAgEACIgLABQgIAAgEABQgCABgJAAQgLAAgDACIgGABQgNAAgEACIgEABIgFAAIgPACIgMAAIgMACQgBABgEAAIgDAAgAhUCQQgCAFgIAHQgCADACACIAHgGQAEgEAEgBIAAgFIgDgCIgCABgAgqCOIAAACIABABIADgCIgBgCIgDABgAABCAIADAIIAHACQgCgCABgGQABgEgDgBgAhyAYQAAAAAAABQgBAAAAABQAAAAABABQAAABAAAAIAEACIACgDIADgHIgDAAQgDAAgDAEgAhdgwIAAALIgBAMQgBADgHAFIgDACQADAFADACIANAFIAYgwQgPACgPgBgAiJgqQgDADgIADIAFAJIACAAIAEgBIAKgEIAGAAQACgIAEgFIACgFIgSgBg");
	this.shape_7.setTransform(264.4,26.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#ED2256").s().p("AkIGIIgKgBQgGgIgEgQIgCgGQgBgEAAgDIgCgDIgDgQIgDgLIgBgFQAAgDgCgCIAAgHIgCgMIAAgIIAAgLQgBgGgCgEIAAgFQAAgKgDgDIgBgFIgCgPIAAh7IABgJIABgKIAAgGQABgEACgCIABgCIABgMIABgLQAEgMgBgGQAGgLAAgNIABgDQAFgMACgOIAFgOIADgJQAAgGACgDIAFgPQACgJAEgFQACgCABgGQADgQALgRIACgGIAPgYIACgEIAMgTQAJgKADgHQAEgDAGgIIAKgMQAFgGABgCQAAgBAAAAQAAAAABgBQAAAAAAgBQABAAABAAIAIgKIAEgGIAGgFQADgDABgEIADgDQAIgIADgGQAEgFAEgCIALgJQAHgIAEgBQAEgCAIgHIAOgKQAJgGAGgCQADgEAJgEQAIgEAEgDIAQgIQAJgFAHgCIACgBQAJgFAXgIIATgGIAegIIAOgCQAFAAAEgCQABgBAFAAIANAAIAFAAQAFgDAIAAIAOAAIACABQAFADAGAAIAMgBIALAAIAEABQAEACAIAAIAMAAQAIAAADACQAEABAHAAQAKAAAEACQACABAHAAQAJAAADACIAEAAQAFgBAJACIAQACIABAIIAAAIQAAAFABADIABAIIAAAuQAAAQACAFIAAAIIAAA1QAAAIADADIABAGQABAqgBArIgBAEQgDADAAAKQAAANgCAGIAAAPQAAAIgGACIgEACIgIADQgCAAgGgDIgVgIIgNgDQgIgCgFgDQgDABgGgCIgJgCIgSgEIgIgBIgHAAQgDgBgDgCIgXAAIgCABQgDAEgJAAIgFAAQgFgBgHACIgMADQgGABgLAGIgQAJIgLAJIgPANQgJAHgGAGIgRATIgNASIgIASIgGAOIgEAMIgIASIgGAOQgBALgBADQAAAFgBAKQgCAKABAFQAAAJgDADIgBAJQAAAFACAEIACADQgBAHADAOIACAMQABAIACAEIADAMQABAKAEAHQABABAAAFQABAEABACQADANAIAZQADAHADAGIAgAgIAHAFIAIAGQgHAFgDAAIgOAAQgHAAgDACIgJABIgHAAQgEAAgEACIgKABQgKAAgEABIgMABQgJAAgDACQgCABgJAAIgHAAQgEAAgDACQgCABgHAAIgIAAQgFAAgDACIgLAAQgKAAgDACIgKABQgLAAgEACIgEABIgEAAIgRACIgKAAQgMABgCACIgIAAIgIAAQgGABgDACIgGAAQgMAAgHACIgGABIgEAAg");
	this.shape_8.setTransform(31.1,40);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#ED2256").s().p("AlTEyIgBgBQAIgQACgIQADgMgEgHQgDgDADgDQAFgFAGgSIAMgnQADgJADgLQABgEACgBQADgDACgFIAFgIQABgBAAgFQAAgLACgDQAAgBAAAAQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgIADgHIAIgaIAMgkQAFgKAAgGQACgDABgGIAEgKIAJgaQAEgSAEgIQAGgWAFgJIABgKIAJgZIAEgQIAGgUIAFgNQADgIAAgGIABgDQAGgPADgTIADgIIAFgSQADgFACgKIAEgQQAEgGgBgFQAAgCABgEIACgGQAAgFADgEQABgEABgGQAAgGAHAAIEwAAQAHAAABABQABABADAGIAIAZIAGASIAZBJIAGASIAMAlIAEAOQABAIAEAHQAFALAHAZIAMAlIAIAYIAIAXIAGAPQACAJADAFQAAAHAFALIANAqIANAlIAMAkQACAEABAKQAGANADAPIADAFQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAIgEAAQgNAAgDACIgHABIgJAAQgGAAgDACIgMAAIgLACQgBABgIAAIgIABQgFAAgEACQgCABgDgBIgFAAQgKAAgEACIgMABQgJAAgDACIgHAAIgJABQgHAAgDACIgEABIgEgBIgIABQgFAAgDABIgLABQgKAAgEACIgDABIgGAAIgHAAQgFAAgDACIgHABQgOAAgEABIgIABIgIAAQAAgEgDgGIgEgJIgDgKIgFgJQgFgMgBgHIgHgSIgPgmQgEABAAAFIgGASQgCAJgCAKIgKAeIgDAOIgJAcIgCAFQgDAEgEAAQgKgBgJADIgJABQgKAAgDACIgEABIgFgBIgIAAQgFABgDACIgHAAIgSACIgNABQgGAAgFACIgJABQgMAAgFACIgDABIgGgBIgOACIgNABIgMACQgBABgIAAIgMACQgCABgFAAIgTACIgNAAQgHAAgEACIgHABIgLAAQgGAAgEADg");
	this.shape_9.setTransform(180.4,32.6);

	this.addChild(this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,380.2,79.2);


(lib.clash_text = function() {
	this.initialize();

	// Calque 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ATaA/QgFgFABgHQgBgFAFgFQAFgFAFABQAHgBAFAFQAEAFAAAFQAAAHgEAFQgFAEgHAAQgFAAgFgEgAR+A/QgIgEgHgIQgFgHgDgKQgCgKgBgMIAAhLIAaAAIAABGIAAAOIADALQACAGAFADQAEAEAIAAQAHAAAFgEQAFgDACgGQACgFABgGIABgOIAAhGIAZAAIAABLQAAAMgDAKQgDAKgGAHQgFAIgJAEQgJAEgNAAQgMAAgKgEgAQAA+QgNgFgHgKQgJgJgFgNQgEgLAAgOQAAgNAEgMQAFgMAJgKQAIgJAMgFQAMgFAOAAQAOAAAMAFQALAFAJAJQAIAJAEANQAFAMAAANQAAAOgFALQgEANgIAJQgJAKgLAFQgMAFgOAAQgPAAgLgFgAQKgmQgHAEgFAFQgFAHgCAHQgDAIAAAHQAAAGACAIQACAIAFAGQAEAHAIAEQAGADALAAQAKAAAHgDQAHgEAEgHQAFgGACgIQACgIAAgGQAAgHgCgIQgDgHgFgHQgFgFgHgEQgHgEgIABQgJgBgHAEgAKrA/QgJgEgGgIQgGgHgDgKQgCgKAAgMIAAhLIAZAAIAABGIAAAOIADALQADAGAEADQAFAEAHAAQAIAAAFgEQAEgDADgGQACgFABgGIAAgOIAAhGIAZAAIAABLQAAAMgDAKQgDAKgFAHQgFAIgJAEQgKAEgNAAQgMAAgJgEgAIsA+QgMgFgIgKQgIgJgFgNQgFgLABgOQgBgNAFgMQAFgMAIgKQAJgJALgFQAMgFAOAAQAOAAAMAFQAMAFAIAJQAJAJAEANQAEAMABANQgBAOgEALQgEANgJAJQgIAKgMAFQgMAFgOAAQgPAAgLgFgAI2gmQgGAEgFAFQgFAHgDAHQgCAIAAAHQAAAGACAIQACAIAEAGQAEAHAIAEQAHADAKAAQAKAAAHgDQAHgEAFgHQAFgGACgIQABgIABgGQgBgHgCgIQgDgHgEgHQgFgFgHgEQgIgEgIABQgIgBgIAEgACvA/QgFgFAAgHQAAgFAFgFQAEgFAGABQAHgBAEAFQAFAFgBAFQABAHgFAFQgEAEgHAAQgGAAgEgEgAg7A+QgMgFgIgKQgIgJgFgNQgEgLgBgOQABgNAEgMQAFgMAIgKQAIgJAMgFQAMgFAOAAQAOAAAMAFQAKAFAIAJQAJAJAEANQAFAMgBANQABAOgFALQgEANgJAJQgIAKgKAFQgLAFgPAAQgOAAgMgFgAgwgmQgHAEgGAFQgEAHgDAHQgCAIgBAHQAAAGACAIQACAIAFAGQAEAHAIAEQAHADAKAAQAKAAAHgDQAHgEAFgHQAEgGAAgIQACgIAAgGQAAgHgCgIQgBgHgFgHQgEgFgIgEQgHgEgIABQgJgBgGAEgAioA8QgKgGgHgMIAQgQQADAIAGAFQAHAGAHAAQAHAAAFgGQAFgFAAgHQAAgFgCgDIgEgGIgHgDIgIgEIgCgBIgLgFQgFgCgEgDQgEgFgCgFQgCgFAAgIQAAgHACgHQADgIAFgFQAFgFAHgDQAIgDAHAAQAJAAAKAEQALAEAGAGIgMASQgEgGgFgCQgEgDgGAAQgHAAgFAEQgEAFAAAFQAAAGAEAEIAPAIIAMAFIAJAHQAFACADAGQACAHAAAJQABATgMANQgLAMgTAAQgOAAgJgHgAn1A/QgFgFABgHQgBgFAFgFQAEgFAGABQAHgBAFAFQAEAFAAAFQAAAHgEAFQgFAEgHAAQgGAAgEgEgAqTA9QgLgEgJgKQgJgJgFgNQgEgLAAgNQAAgMAEgMQAFgNAJgKQAIgJAMgFQAMgGAOAAQAPAAANAIIAAAdQgGgGgHgEQgIgDgHAAQgJAAgHADQgHAEgFAGQgFAHgCAIQgDAHAAAHQAAAIADAIQACAHAFAHQAFAGAHADQAHAEAJAAQAHAAAIgEQAHgEAGgFIAAAdIgPAGQgHACgIAAQgNAAgLgGgAwxA+QgMgFgIgKQgJgJgEgNQgFgLABgOQgBgNAFgMQAEgMAJgKQAJgJALgFQAMgFAOAAQAOAAAMAFQAMAFAIAJQAIAJAFANQAFAMAAANQAAAOgFALQgFANgIAJQgIAKgMAFQgMAFgOAAQgPAAgLgFgAwmgmQgIAEgEAFQgGAHgCAHQgDAIAAAHQABAGACAIQACAIAEAGQAFAHAHAEQAHADAKAAQAKAAAHgDQAIgEAEgHQAEgGADgIQACgIAAgGQgBgHgCgIQgCgHgFgHQgGgFgHgEQgGgEgJABQgJgBgGAEgAzCBDIgxiCIAbAAIAfBUIAAAAIAdhUIAbAAIgzCCgACFBCIhDhYIgBAAIAABWIgYAAIAAiCIASAAIBDBXIAAAAIAAhUIAaAAIAACBgArXBCIhDhYIgBAAIAABWIgZAAIAAiCIASAAIBDBXIABAAIAAhUIAZAAIAACBgAG4BBIgchPIAAAAIgLBOIgZAAIAViCIARAAIAhBSIAdhSIASAAIAUCCIgaAAIgKhOIAAAAIgdBPgAOSBAIAAh/IBAAAIAAAWIgoAAIAAAdIAlAAIAAATIglAAIAAA5gAM6BAIgfg0IgBAAIAAA0IgYAAIAAh/IAhAAQAVAAALAKQALAJAAAUQABANgIAKQgGAJgNACIAkA2gAMagEIAEAAQALAAAHgEQAFgEAAgLQAAgMgFgEQgHgDgLAAIgEAAgAFdBAIgKgbIgtAAIgKAbIgbAAIAyiCIATAAIAxCCgAFMAQIgRgtIAAAAIgOAtIAfAAgAjfBAIAAh/IAZAAIAAB/gAkFBAIggg0IAAAAIAAA0IgZAAIAAh/IAiAAQAUAAAMAKQALAJAAAUQAAANgHAKQgHAJgNACIAlA2gAklgEIAEAAQALAAAGgEQAGgEAAgLQAAgMgGgEQgGgDgLAAIgEAAgAmYBAIAAh/IAiAAQAVAAAMAKQALAJAAAVQAAAUgKAIQgLAKgTAAIgNAAIAAAxgAl/gDIAGAAQAMAAAFgEQAFgEAAgMQAAgMgFgDQgHgEgLAAIgFAAgApNBAIAAh/IBDAAIAAAWIgqAAIAAAdIAoAAIAAATIgoAAIAAAjIAqAAIAAAWgAuHBAIAAh/IBDAAIAAAWIgqAAIAAAdIAoAAIAAATIgoAAIAAAjIAqAAIAAAWgAvLBAIAAh/IAZAAIAABpIAjAAIAAAWgAx8BAIAAh/IAZAAIAAB/g");
	this.shape.setTransform(131.1,12.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(4.2,5.9,253.7,13.5);


(lib.clash_bottom = function() {
	this.initialize();

	// Calque 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#ED2256").s().p("AAAACIAAgDIAAAAIABADg");
	this.shape.setTransform(36.2,53.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#ED2256").s().p("AgBAAIADgCQABACgBADg");
	this.shape_1.setTransform(43.3,60);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#ED2256").s().p("AgBAAIABAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIABABIgCACg");
	this.shape_2.setTransform(53.6,59.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#ED2256").s().p("AAAgBIABACQAAAAAAAAQAAAAgBAAQAAABAAAAQAAAAAAAAg");
	this.shape_3.setTransform(43.7,59.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#ED2256").s().p("AAAACQAAAAAAAAQAAAAAAAAQAAgBAAAAQgBAAAAgBIABgBIACABQAAAAAAABQAAAAAAABQgBAAAAAAQAAAAAAAAIgBAAg");
	this.shape_4.setTransform(37.4,62);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#ED2256").s().p("AgBAAQgBAAAAAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAgBAAAAQAAAAAAAAQAAAAAAABIADABIgDABQAAAAAAAAQAAgBAAAAQAAAAAAAAQgBgBAAAAg");
	this.shape_5.setTransform(34.6,57.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#ED2256").s().p("AAAAAQAAgDgCgCIACgBQAGAGgFAGIgBABQAAgCAAgFg");
	this.shape_6.setTransform(37.6,48.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#ED2256").s().p("AgDgCQADgDAEAFIgDAEg");
	this.shape_7.setTransform(47.5,60.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#ED2256").s().p("AgEADQACgDACgCQAEgCABAEIgFADIAAAAIgEAAg");
	this.shape_8.setTransform(49.3,59.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#ED2256").s().p("AgEADIAAgBIAAgBIAFgFIADABIABABIgBACIgEAEIgBABIgDgCg");
	this.shape_9.setTransform(36.1,51.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#ED2256").s().p("AgCACIgFgBQACgBAFgBQADgCACgDIADAHIgGAGg");
	this.shape_10.setTransform(39.5,64.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#ED2256").s().p("AgKAIQgCgDABgFIALgCQAFgCACgCQACgCADABIAAAAIgKAPQgGgDgGADg");
	this.shape_11.setTransform(37.9,55.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#ED2256").s().p("AgJAAQgBAAABgDQABgDACgCQABAAAAAAQAAAAABAAQAAAAABAAQAAAAAAAAIANAHIgLAKg");
	this.shape_12.setTransform(53.5,48.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#ED2256").s().p("AAHAcIgBgDIgCgOIAAgHIgBgIIgHgFQgDgBgCgEQgEgGAFgEIAGgFQACACAAAEQgBAKAGACIADALIADAKQABACgBAFIgCAEIAAADIACAHIgEgDg");
	this.shape_13.setTransform(50.1,52.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#ED2256").s().p("AgbAVQAFgJgDgHQgCgCgGABQgGAAgDgEQACgEAFgBQABgBAAABQABAAABAAQAAAAABAAQAAABABAAIADADIATgCIAEgMIAFAKIAFAAQAGABADgHIAGgHIAIgBIAIgCIAGABQgFACgFAFIgKAHQgFADADADQAEAGgEAEIgFAEQgDACgDgCQgCgCgFAAQgDAAgBgCQgBgBAAAAQAAAAAAAAQgBAAAAAAQAAAAAAABQgDACgEAAIgIAAIgDAIQAAABAAAAQgBABAAAAQgBAAAAAAQAAAAgBAAIgDgBg");
	this.shape_14.setTransform(48.2,63.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#ED2256").s().p("AgdAxIABgCQAEgEAAgEIABgHIgJgNIgGgEIADgHIAUgFIAEgJIgHgNIgOgFIgCAGIgBgGQAAgFgCgCIAFgLIAGgJQACgEAEAAQAEAAABAFIgKALIAIALQACABALADIgCALIALAHQAJADAHgHIARAIQADADgFAGIgVAMQgBgIgGgEQgCgCgJgEIgNAGIABAHIAGALQACAFgCACIgMAVIgEADg");
	this.shape_15.setTransform(42.7,56.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#ED2256").s().p("AAAAOQgEAAgDgEQgEgFgBgDIAAgIIAAgHIAQAAIAJAJIAAARIgKABIgDAAg");
	this.shape_16.setTransform(234.7,31.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#ED2256").s().p("AgIANQgDgBgCgDQAAAAAAgBQAAgBAAAAQAAgBAAgBQAAAAAAgBIADgGQABgFACgDIADgHIAIACQAEABADAGQAEAFgBADQgBALgIAHQgIgEgFgBg");
	this.shape_17.setTransform(141.4,78.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#ED2256").s().p("ADiC4IgXAAQgKAAgCgCIgHgBIgYAAQgNAAgEgCIgHgBIgfAAQgHAAgDgBIgCgBIgKAAQgGgBgDgCQgGAAgIgCIgMgEIg7gTQgHgEgMgEIgUgHQgXgKgRgJQgUgLgMgKQgOgKgDgCIgFgEIgEgFIgGgEIgEgDIgagaQgCgFgLgKQgFgGAAgCIgCgCQgIgIgPgVIgUgdIgCgEIgGgMQgFgFgFgNIgJgPIgGgMQAAgEgFgIQgGgLgBgGQgGgHAAgFQAFgEALAAQAMAAAFgDQACgBAIABQALAAACgCIAHgBIAQgCIANAAIAKgCIAJgBIAIgBQAGAAACgCIAHAAQAOAAAFgCIAMgBQALAAAEgCQACgBAGAAQANAAAEgCIAKAAIAHgBIAHgBIAMgBIAGAAIAGgCQABgBAGAAIAJAAQAGAAAEgCQADgCAIABQAIAAACgBIAPgBQAIgBAGADQANAFAJAMIAEAIIAGgFIAnARQAKAFAFgBIAIACIAQAFQAEAAAFACIAJADIgDAaQgCABgFAAIgIABIgHAMQACAGADACQADAGgDAGQgDAEgBAGQAAAAAAAAQAAABAAAAQAAAAABABQAAAAABABQAAAAAAAAQABAAAAAAQAAAAABAAQAAAAABgBIAGgFIADgFQADgCADgBIADgCQAFgFAHgGIAPgKIAGgCIAGgLQACgEADgBIAJgEQAFgDAEgBQADAAAEgEQgHgCgCgJIgDgIIATgUQAJgCAHAFIANgNIAMACQAFAAACAFQAGARgGASQgEAFAEAFQAFAKgFANIgDAEQgCACgEgBQgFgBgCADQADABAFAFQAEAEAEABQAAAAAAAAQABABAAAAQABABAAAAQAAABAAABIABAKQAAAGgEAEIADAGIAAAIIAAAWQgBABgFAAQgEABgBACIgEAAQgDgDgBAEQgDAEADADIAHAGIgGAIQABAHAIAEIAMAFQABAAAAABQAAAAAAAAQAAABAAAAQAAABgBAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAIADAGQADAHAAAIIAAAaQAAAJACACIABAGIAAARQAAAKACAEIABAGIAAAWQAAAGgGACIgVALIgNAFQgGADgGAAQgEADgGAAIgLAAgACcBJQACAHgFAJQAEADADgEIADgIIAHAAQAFAAACgCQABAAAAgBQAAAAAAAAQABAAAAAAQAAABAAAAQACACAFAAQAFAAACACQADACADgCIAFgEQAEgEgEgGQgDgFAFgDIAJgHQAGgFAEgCIgFgBIgIACIgIABIgGAHQgDAHgGgBIgFAAIgHgKIgEAMIgUABQgDgEgEABQgFABgCAGQADAEAGAAIACAAQAEAAACABgABeBLQgFACgCACIAFABIAGAFIAGgGIgDgJQgCADgFACgABsgTIAHANIgEAJIgTAFIgEAHIAGAEIAJANIgBAHQAAAEgEAEIgBACIAFAHIADgDIAMgVQADgCgDgFIgGgLIgBgHIANgGQALAEACACQAGAEABAIIAWgMQAEgGgCgDIgSgIQgHAHgJgDIgMgHIABgLQgLgDgBgBIgIgLIAKgLQgCgFgEAAQgEAAgCAEIgGAJIgFALQACACABAFIAAAGIADgGgABIA1QAAAAABABQAAAAAAAAQABABAAAAQAAAAABAAQAAAAABAAQAAAAAAgBQABAAAAAAQAAgBAAgBIgDgDgACrAgIAGAIIADgFQgDgEgDAAIgDABgACDAfIAFAEQACgEgCgDgADrAbIgBACIACACIADgCIgBgDIgBAAIgCABgADCAUQgEADgCAEIAFABIAFgEQAAgBAAgBQAAgBgBAAQAAgBgBAAQAAAAgBAAIgBAAgACIAcQABAAABgBQAAAAABAAQAAAAAAAAQABAAAAgBIgBgDgAArAKQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABQADADAEgCIgEgDIgBgBIgCABgABTgBIAJgRIAAAAQgBAAAAAAQgBAAAAAAQgBAAgBAAQAAAAgBABQgCACgFACIgMADQgCAGACADIAGgCQAEAAAFACgADBhBQgGAFAEAFQACAFADABIAJAEIABALIAAAHIADAOIAAADIAEACIgCgGIABgEIABgDQABgFgBgCIgDgLIgDgMQgIgCABgKQABgFgDgCIgFAFgAA9gdIACAAIgBgFIgBAAgAA+g5IgGAGIAAACIAAABQABAAAAABQABAAAAAAQABAAAAAAQAAAAAAAAIAHgGIABgCIgBgCIgDAAIgBAAgABIhTQADACAAAFQgBAFACABIACgBQAFgHgIgGgADlhaQgDACgBADQgBADABACIAIAJIAOgMIgQgHIgBAAIgBAAg");
	this.shape_18.setTransform(29.9,56.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#ED2256").s().p("AB4DdQgFgDgOAAImDAAQgNAAgHgJIgEgEIAAhtQAAgJACgFIABgJIAAiqIgBgLIACgKQADgGgDgGQgDgHADgGQADgHgCgFIgCgOQAAgFgCgCQgCgDABgKIADAAIAKgBQAGgBADgBIAKAAIAHgBQAEAAACgCIAFgBQAMAAAGgCIAPAAQAHAAAEgCQADgCAHABQAMAAADgCIAIgBIAJAAIAJgCIAKAAIAOgCIAJgBIAIAAQAEAAAEgDQACgBAIABQAKAAAEgCQACgBAHAAQAMAAAEgBIAJgBIAIAAQAFAAADgCIAFAAIAABEQAAAIACADIABAHIAAAUQADAFAPAKQAGAEAHAAIAdgBQAHAAADgBQACgBAIAAICXAAQALAAAEgCIAHAAIBQAAQADAAADADIABAEQAIAHgGAKIgDAHQgEAGADADQADAEgCACQgDAFgCANIgGALIgIAMIAAAHIgCAPQgCAJgEAHQgCAFgDAPIgCAJQgEAHABAGQAAAGgDALIgEAKQgCAIgIATIgBACQgIAIAGAGIgBAMIgEANIgDANIgEAOQgCAGgFAEQgKAIgOAHQgLAGgLAAg");
	this.shape_19.setTransform(98.6,53.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#ED2256").s().p("Ag+FCQgGAAgBgBQgDgCgKAAIibAAQgQAAgHgKIgDgDIAAivQAAgJADgEQABgBAAgIIAAhNQAAgGAFgCIAFgEQAMgHAKAAIAOAAIAOACIAIABQAFAAADACIAGAAIAMACQABABAGAAIAZAAQAPABAUgJQASgGAEgKIADgEIAEgIIADgMQABgIgBgFIAAgCQABgIgGgXQgDgJgGgGQgKgPgHgFQgFgFgCgGQgCgHgGgFIgpgpIgngoIgEgDQgEADgRAAQgFABgBgFQgCgFgEgFIgJgJIAAgBQgBgGACgGIADgMIACgGQgBgDACgFIACgIIAHgBQAWgDAIAAQAFgCAQAAIAFgBQAEgCAKAAQALAAAEgCIAGgBQAOAAAFgCQAEgCAKABQAJAAADgBQACgBAGAAIAJAAIAJgCIAMgBQAIAAADgCIAIgBIAJAAQAGAAADgCQACgBAHAAQAKAAADgCIADAAIADAAQAMAAAEgCIAMgBIALgCIAJgBIARgCIANAAIAKgCQAJgCAHACQAFAAAHAHIA1A1IAIAKQAGAIABACIAEAFQAEADAAADQADACAEAHQACAHAEACQACAIAHANIAIATQAEAHAAAGQABAGAEAKIAEAUIACAGIABACQgBAFACAIQACAIAAAEQgBAHACAGQABABAAAHIAAAeQAAAHACADQAEAFgEAHIgFAQQgCAHAAAJQAAAHgCACIgBABQABAHgEAMIgGAZIgNAmIgFANQgFAPgDAFQgDAEgCAIQgHAOgNATQgKARgRAQIgXAXIgIAGIgEAEQgIAHgQAKQgbASgVAGIgPAEQgLACgNAJQgJAFgCADIgIAEQgGACgFAAg");
	this.shape_20.setTransform(262.7,43.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#ED2256").s().p("AlUE6IgJgIQgFgFADgGQAGgLAFgFQgHgJAAgIQAAgEgDgCQgDgDgEACQgHADgVAAQgJgBgMAFQgJAEgIgEQgGgDgFACQgFADgKgEQgFgCgGAAIgdAAIgEgGIgDgDQgGgFADgGQACgDABgIIAEgLIADgOQABgJACgEIADgJIACgJIADgPIADgHIAFgSIAEgKIACgKQABgHADgEIAFgNQAHgPABgIIACgHIAAgEQADgGAAgIQACgDAAgHQABgHACgDQgBgCACgEIACgFIALgkIAKggIAJgcIABgEQADgDgCgIQgLgBgDgKIgCgCIgDgGQAAgBAEgEIAHgIQAGgHAIAEIAGABQAFgFACgLIADgMIACgEQABgDgCgCQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAgBAAgBIgBgFQgDgEAEgEQALgLAGgQIgCgEQgDgLAKgDIAIgDQAFgBADAAQAKACAHgEIAIAAQAMAAAEgCIAMgBQAJAAADgCIAHgBQAMAAADgCIAHAAIAJAAIAJgCIANgBIAPgCIAIgBIAIAAQAFAAADgCQADgCAIABQAJAAAFgBQADgCAJABQAJAAADgCIAHgBIAJAAQAGAAAEgCIAIgBIAIAAIAIgCIAMAAQAIAAAEgCIAIgBQABAGgCAFIgNAoIgCAJQgJAZgCAJQgCACAAAEIgCAFIgBAGIAFABIBMAAIAFgBQAMgEAPAEIAMAEQAIAFAKgFIADgCIAAgPQAAgNACgFQACgHgEgJQgIgRgBgJQgEgFgDgJQgDgLgDgEQgCgDgBgGIgCgKQACgBAHAAQAJAAAFgCQACgBAKAAQAJAAADgCIAIgBQAOAAAEgCIAIAAIAQgCIAOgBIAHAAQADAAADgCIAGgBIAKAAIAKgCIALAAQAIAAAEgCQADgCAHABQAMAAADgCIAIgBIARgCIANAAIAKgCIAKgBIAMgCQAEgCAIABQAFAAACAGIAKAjIACAJIgCAIQAIAIABAJIAAABQAGAIAGAUIABAFQAAAGAGAPQACADAAADIACANQACAHgBAGQAGAFAAABIAHAVIAGAVQAEAGADAOIAIAZIAJAeIAEAKIAFATIAGAOIACAJIADAIQADAFACAMIAIAcIABADQADAGAAADIgEAJIAGAGQAHAHAHASIAIAXIADAMIAFALQABADABAIIAKAfIAHAXIgFAGIgFAHIgHABQgFAAgDACIh+AAIgEgFIgCABQgFAFgIgBIg9AAQgGAAgEgCIgJgBIgxAAQgDgHgBgDIgFgRIgFgRIgNgoIgEgLIgDgJQgEgHgIgDIgcgIQgHgBgDABQgEACgKAAIgPAAQgGAAgDACIgIABIgiAAIgHAAQgFADgNAAIiGAAQgLAAgEABQgBABgGAAIgTAAQgMAWgGATIgBADQgDAEgCAJIgFANIgHARQgFAKgBAGIgEAIQgCAEgEAAIgMACQgIACgHgCIgMgCIgGgBQgKgEgHAFQgDACgFAAQgFABgCABQgBgBgFAAQgEAAgCgCIgHgDQgDABgCAEIgDAGIgHAIQgCACgGABQAAAAAAABQAAAAAAABQABAAAAABQABAAABAAIAJAFQAHAEAAAFQAAAAAAABQAAABAAAAQAAABAAAAQABAAAAAAQADAEgEAGQgHAKgMAAIgHgBg");
	this.shape_21.setTransform(178.5,49.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#ED2256").s().p("Al7F6IgCgCIgLgLIAAgNIAAmkQAAgMACgEIABiuQAAgKABgCIAFgBQAKgBgEgKIgEgIIACgCQACAAAHgBIAJgCQALABAHgDIALgBQAIAAADgCIAHAAIAMAAQAHAAAFgCIAJgBQAKAAADgCQADgBAGAAQANAAAEgCIAJAAIAIAAQAEgBADgBIAGgBQANgBACgCIALAAQALAAADgCQACgBAHAAQAMAAAEgCIACAAQAGgBACADQABACgBAGIAAACIAEABIDsAAQAMAAAEADIAHAAQABgEAAgSIAAgUIAGgEIALgCQAHgCAEAAQALABAEgCIAIgBIAJAAQAFAAAEgCIAKgBQAIAAAGgCQADgBAJAAQAJAAACgCIAIAAIAJAAQAGAAADgCIALgBIAIAAIAIgCIALgBIAOgCQACgBAIAAQAKAAAFgBQACgCAFABQANAAAEgCIAIgBIAIAAIABBVQAAAIABAEQABACAAAIIAABfQABANADADIAAAGIAABgQAAAGgCADQgBAAAAABQAAAAAAABQAAAAAAABQgBABAAAAIAAGSQABAGgFADIgIAFQgEADgFgCIgIAAIhGAAQgKAAgEABIgGABIh/AAIgBgBIgLgLIAAgPIAAgbQAAgJACgEIAAgKIAAlGQgCgCgHAAIhBAAQgMAAgEgCIgGgBIilAAIgHABIAAAFIAAAaQAAAIgCAEIgBAFIAAAXQACAFABAHIAAAOIAABKQgBAIACACIABAIIAABoIgBAFQgBAEAAAOIAAAgIgBAJQAAAFACAEIABACIgBAdIgHADIgGAGIgIABQgFAAgCACIgIABg");
	this.shape_22.setTransform(337.5,37.9);

	this.addChild(this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,376.9,81.5);


(lib.books = function() {
	this.initialize();

	// Calque 1
	this.instance = new lib.book1();
	this.instance.setTransform(66.3,8.8,0.664,0.664);

	this.instance_1 = new lib.book2();
	this.instance_1.setTransform(0,0,0.664,0.664);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,150,149.7);


(lib.slogan = function() {
	this.initialize();

	// Calque 1
	this.instance = new lib.jay_crownover();
	this.instance.setTransform(114.2,88.1,1.289,1.286,0,0,0,89.2,8.8);
	this.instance.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,10);

	this.instance_1 = new lib.nouvelle_serie();
	this.instance_1.setTransform(111.7,9.6,1.042,1.041,0,0,0,115.8,9.2);
	this.instance_1.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,8);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-13,-4,262,113.8);


(lib.btn = function() {
	this.initialize();

	// Calque 2
	this.instance = new lib.discover_bold();
	this.instance.setTransform(55.7,9.4,0.56,0.562,0,0,0,62.6,10.3);

	// Calque 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#51A5B6").s().rr(-68.2,-10.55,136.4,21.1,2);
	this.shape.setTransform(55.4,10.5,0.812,1);

	this.addChild(this.shape,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,110.8,21.1);


// stage content:
(lib.clash_300x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{loop_btn:174});

	// timeline functions:
	this.frame_196 = function() {
		this.gotoAndPlay('loop_btn');
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(196).call(this.frame_196).wait(1));

	// btn
	this.instance = new lib.btn();
	this.instance.setTransform(150,562.4,1.218,1.217,0,0,0,55.4,10.5);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(150).to({_off:false},0).to({scaleY:1.22,x:149.9,y:539.6,alpha:1},14,cjs.Ease.get(1)).wait(10).to({scaleX:1.07,scaleY:1.07},11).to({scaleX:1.22,scaleY:1.22},11).wait(1));

	// books
	this.instance_1 = new lib.books();
	this.instance_1.setTransform(150,218.9,0.303,0.303,0,0,0,75,74.7);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(60).to({_off:false},0).wait(1).to({regY:74.8,scaleX:0.31,scaleY:0.31,alpha:0.002},0).wait(1).to({scaleX:0.31,scaleY:0.31,alpha:0.008},0).wait(1).to({scaleX:0.32,scaleY:0.32,alpha:0.019},0).wait(1).to({scaleX:0.34,scaleY:0.34,y:219,alpha:0.034},0).wait(1).to({scaleX:0.36,scaleY:0.36,alpha:0.053},0).wait(1).to({scaleX:0.38,scaleY:0.38,y:219.1,alpha:0.077},0).wait(1).to({scaleX:0.41,scaleY:0.41,y:219.2,alpha:0.105},0).wait(1).to({scaleX:0.44,scaleY:0.44,y:219.3,alpha:0.137},0).wait(1).to({scaleX:0.48,scaleY:0.48,y:219.4,alpha:0.174},0).wait(1).to({scaleX:0.52,scaleY:0.52,y:219.5,alpha:0.215},0).wait(1).to({scaleX:0.56,scaleY:0.56,y:219.7,alpha:0.26},0).wait(1).to({scaleX:0.61,scaleY:0.61,y:219.8,alpha:0.308},0).wait(1).to({scaleX:0.66,scaleY:0.66,y:220,alpha:0.359},0).wait(1).to({scaleX:0.71,scaleY:0.71,y:220.2,alpha:0.413},0).wait(1).to({scaleX:0.77,scaleY:0.77,y:220.4,alpha:0.469},0).wait(1).to({scaleX:0.83,scaleY:0.83,y:220.5,alpha:0.528},0).wait(1).to({scaleX:0.89,scaleY:0.89,y:220.7,alpha:0.588},0).wait(1).to({scaleX:0.95,scaleY:0.95,y:220.9,alpha:0.649},0).wait(1).to({scaleX:1.01,scaleY:1.01,y:221.1,alpha:0.712},0).wait(1).to({scaleX:1.07,scaleY:1.07,y:221.3,alpha:0.775},0).wait(1).to({scaleX:1.13,scaleY:1.13,y:221.5,alpha:0.838},0).wait(1).to({scaleX:1.19,scaleY:1.19,y:221.7,alpha:0.895},0).wait(1).to({scaleX:1.23,scaleY:1.23,y:221.8,alpha:0.937},0).wait(1).to({scaleX:1.26,scaleY:1.26,y:221.9,alpha:0.967},0).wait(1).to({scaleX:1.28,scaleY:1.28,alpha:0.986},0).wait(1).to({scaleX:1.29,scaleY:1.29,y:222,alpha:0.997},0).wait(1).to({scaleX:1.29,scaleY:1.29,x:150.1,y:221.9,alpha:1},0).to({scaleX:1.44,scaleY:1.44},52).wait(1).to({scaleX:1.44,scaleY:1.44,y:223.8},0).wait(1).to({scaleX:1.43,scaleY:1.43,x:150,y:226.2},0).wait(1).to({scaleX:1.42,scaleY:1.42,y:229},0).wait(1).to({scaleX:1.41,scaleY:1.41,x:149.9,y:232.2},0).wait(1).to({scaleX:1.4,scaleY:1.39,y:235.7},0).wait(1).to({scaleX:1.38,scaleY:1.38,x:149.8,y:239.7},0).wait(1).to({scaleX:1.37,scaleY:1.37,x:149.7,y:243.9},0).wait(1).to({scaleX:1.35,scaleY:1.35,y:248.4},0).wait(1).to({scaleX:1.34,scaleY:1.34,x:149.6,y:253.1},0).wait(1).to({scaleX:1.32,scaleY:1.32,x:149.5,y:258},0).wait(1).to({scaleX:1.3,scaleY:1.3,x:149.4,y:262.9},0).wait(1).to({scaleX:1.29,scaleY:1.29,y:267.9},0).wait(1).to({scaleX:1.27,scaleY:1.27,x:149.3,y:272.8},0).wait(1).to({scaleX:1.26,scaleY:1.26,x:149.2,y:276.1},0).wait(1).to({scaleX:1.25,scaleY:1.25,y:277.6},0).wait(1).to({regX:74.8,scaleX:1.25,scaleY:1.25,y:278.1},0).wait(42));

	// books text
	this.instance_2 = new lib.slogan();
	this.instance_2.setTransform(148.8,373.3,0.773,0.773,0,0,0,116,49.6);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(79).to({_off:false},0).to({scaleX:1,scaleY:1,x:149.9,y:399.4,alpha:1},38,cjs.Ease.get(0.5)).to({scaleX:1.06,scaleY:1.06,x:149.8,y:407},22,cjs.Ease.get(-0.5)).wait(1).to({regY:51,scaleX:1.06,scaleY:1.06,y:409.9},0).wait(1).to({scaleX:1.06,scaleY:1.06,y:411.6},0).wait(1).to({scaleX:1.06,scaleY:1.05,y:413.7},0).wait(1).to({scaleX:1.05,scaleY:1.05,x:149.7,y:415.9},0).wait(1).to({scaleX:1.05,scaleY:1.05,y:418.4},0).wait(1).to({scaleX:1.05,scaleY:1.05,y:421.2},0).wait(1).to({scaleX:1.04,scaleY:1.04,y:424.2},0).wait(1).to({scaleX:1.04,scaleY:1.04,x:149.6,y:427.3},0).wait(1).to({scaleX:1.04,scaleY:1.03,y:430.6},0).wait(1).to({scaleX:1.03,scaleY:1.03,y:434},0).wait(1).to({scaleX:1.03,scaleY:1.03,x:149.5,y:437.5},0).wait(1).to({scaleX:1.03,scaleY:1.02,y:441.1},0).wait(1).to({scaleX:1.02,scaleY:1.02,y:444.7},0).wait(1).to({scaleX:1.02,scaleY:1.01,y:448.1},0).wait(1).to({scaleX:1.02,scaleY:1.01,y:449.6},0).wait(1).to({regY:49.6,y:448.5},0).wait(42));

	// clash_top
	this.instance_3 = new lib.clash_top();
	this.instance_3.setTransform(95.4,215.3,0.598,0.598,0,0,0,190.1,39.6);
	this.instance_3.alpha = 0;
	this.instance_3.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,8);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({scaleX:0.56,scaleY:0.56,x:149.4,y:213,alpha:1},17,cjs.Ease.get(-0.5)).to({regX:190,scaleX:0.57,scaleY:0.57,x:143.3,y:211.7},42).to({regX:190.1,scaleX:0.65,scaleY:0.65,x:118.5,y:185.1,alpha:0},14,cjs.Ease.get(1)).to({_off:true},1).wait(65).to({_off:false,regX:190.2,scaleX:0.53,scaleY:0.53,x:145.4,y:67.7},0).to({x:146.4,alpha:1},25,cjs.Ease.get(-0.5)).wait(33));

	// clash_bottom
	this.instance_4 = new lib.clash_bottom();
	this.instance_4.setTransform(201.8,264.9,0.598,0.598,0,0,0,188.5,40.6);
	this.instance_4.alpha = 0;
	this.instance_4.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,8);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({regX:188.6,scaleX:0.56,scaleY:0.56,x:155.8,y:237.2,alpha:1},17,cjs.Ease.get(-0.5)).to({regX:188.5,regY:40.5,scaleX:0.57,scaleY:0.57,x:161.1,y:235.4},42).to({scaleX:0.65,scaleY:0.65,x:182.8,y:264.9,alpha:0},14,cjs.Ease.get(1)).to({_off:true},1).wait(65).to({_off:false,regX:188.6,scaleX:0.53,scaleY:0.53,x:151.4,y:90.5},0).to({x:152.4,alpha:1},25,cjs.Ease.get(-0.5)).wait(33));

	// clash text
	this.instance_5 = new lib.clash_text();
	this.instance_5.setTransform(150.7,291.1,0.911,0.911,0,0,0,131.7,12.8);
	this.instance_5.alpha = 0;
	this.instance_5.shadow = new cjs.Shadow("rgba(0,0,0,1)",0,0,8);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(15).to({_off:false},0).to({scaleX:1.12,scaleY:1.12,y:301.1,alpha:1},44,cjs.Ease.get(1)).to({_off:true},1).wait(79).to({_off:false,regX:131.6,scaleX:1.1,scaleY:1.09,x:151.8,y:152.5,alpha:0},0).to({alpha:1},25).wait(33));

	// logo
	this.instance_6 = new lib.logo();
	this.instance_6.setTransform(252.1,550.1,0.8,0.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(197));

	// bg
	this.instance_7 = new lib.background();

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(197));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(123.7,300,356.4,600);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;